#!/bin/bash
################################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2.0
##  \   \         Application : Virtex-6 IBERT Core
##  /   /         Filename : implement_sh.ejava 
## /___/   /\     Timestamp :
## \   \  /  \
##  \___\/\___\
##
##
## implement.sh script 
## Generated by Xilinx Virtex-6 IBERT Core
##
#-----------------------------------------------------------------------------
# Script to synthesize and implement the RTL provided for the IBERT core
#-----------------------------------------------------------------------------
#Exit on Error enabled.
set -o errexit

#Create results directory
rm -rf results
mkdir results

echo 'Running Coregen on ICON required for example design'
coregen -b chipscope_icon_1.xco -p coregen.cgp
# Check Results
if [ $? -gt 0 ] ; then 
echo An error occurred running Coregen on ICON
echo FAIL
exit
fi

cp ../../ibert.ngc .

##-------------------------------Run Xst on Example top----------------------------
echo 'Running Xst on example top'
xst -ifn example_implement_ibert.xst -ofn example_core.log -intstyle silent
# Check Results
if [ $? -gt 0 ] ; then 
echo An error occurred running XST on example_ibert
echo FAIL
exit
fi

cp chipscope_icon_1.ngc ./results
cp ../../ibert.ngc        ./results
cp example_ibert.ngc        ./results
cd ./results
##-------------------------------Run ngdbuild---------------------------------------
echo 'Running ngdbuild'
ngdbuild -uc ../../example_design/ibert_top.ucf -p xc6vlx130t-ff1156-1 -sd . example_ibert.ngc example_ibert_top.ngd
if [ $? -gt 0 ] ; then 
echo An error occurred running NGDBUILD on example_ibert 
echo FAIL
exit
fi
#end run ngdbuild section
##-------------------------------Run map-------------------------------------------
echo 'Running map'
map -w -p xc6vlx130t-ff1156-1 -o example_ibert_top.map.ncd example_ibert_top.ngd
if [ $? -gt 0 ] ; then 
echo An error occurred running MAP on example_ibert 
echo FAIL
exit
fi
##-------------------------------Run par-------------------------------------------
echo 'Running par'
par -w -ol high example_ibert_top.map.ncd example_ibert_top.ncd 
if [ $? -gt 0 ] ; then 
echo An error occurred running PAR on example_ibert 
echo FAIL
exit
fi
##---------------------------Report par results-------------------------------------
echo 'Running design through bitgen'
bitgen -d -g GWE_cycle:Done -g GTS_cycle:Done -g DriveDone:Yes -g StartupClk:Cclk -w example_ibert_top.ncd
if [ $? -gt 0 ] ; then 
echo An error occurred running BITGEN on example_ibert 
echo FAIL
exit
else
echo PASS
exit
fi
