config alt_a10_lpm_shiftreg_cfg;
		design alt_a10_lpm_shiftreg;
		instance alt_a10_lpm_shiftreg.lpm_shiftreg_0 use alt_a10_lpm_shiftreg_lpm_shiftreg_151.alt_a10_lpm_shiftreg_lpm_shiftreg_151_m6wkfty;
endconfig

