#ChipScope Core Inserter Project File Version 3.0
#Wed Jan 08 01:25:38 CET 2014
Project.device.designInputFile=M\:\\project_gbt\\hdl_projects\\new_structure_20_40_xlx_7\\example_designs\\xilinx_k7v7\\kc705\\ise_project\\kc705_gbt_example_design_cs.ngc
Project.device.designOutputFile=M\:\\project_gbt\\hdl_projects\\new_structure_20_40_xlx_7\\example_designs\\xilinx_k7v7\\kc705\\ise_project\\kc705_gbt_example_design_cs.ngc
Project.device.deviceFamily=20
Project.device.enableRPMs=true
Project.device.outputDirectory=M\:\\project_gbt\\hdl_projects\\new_structure_20_40_xlx_7\\example_designs\\xilinx_k7v7\\kc705\\ise_project\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=2
Project.filter<0>=
Project.filter<1>=*mgt*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=1
Project.unit<0>.clockChannel=gbtExmplDsgn FABRIC_CLK_I
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=rst RESET_O
Project.unit<0>.dataChannel<10>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i QPLL_RESET
Project.unit<0>.dataChannel<11>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i SOFT_RESET
Project.unit<0>.dataChannel<12>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i STABLE_CLOCK
Project.unit<0>.dataChannel<13>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i TXRESETDONE
Project.unit<0>.dataChannel<14>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i TXUSERCLK
Project.unit<0>.dataChannel<15>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i TXUSERRDY
Project.unit<0>.dataChannel<16>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i CPLLLOCK
Project.unit<0>.dataChannel<17>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i CPLLREFCLKLOST
Project.unit<0>.dataChannel<18>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i GTRXRESET
Project.unit<0>.dataChannel<19>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i PHALIGNMENT_DONE
Project.unit<0>.dataChannel<1>=gbtExmplDsgn gbtBankRst GBT_TXRESET_O
Project.unit<0>.dataChannel<20>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i RECCLK_STABLE
Project.unit<0>.dataChannel<21>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i RXDFEAGCHOLD
Project.unit<0>.dataChannel<22>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i RXDFEAGCHOLD_glue_set
Project.unit<0>.dataChannel<23>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i RXLPMHFHOLD
Project.unit<0>.dataChannel<24>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i RXRESETDONE
Project.unit<0>.dataChannel<25>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i RXUSERCLK
Project.unit<0>.dataChannel<26>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i RXUSERRDY
Project.unit<0>.dataChannel<27>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i SOFT_RESET
Project.unit<0>.dataChannel<28>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i STABLE_CLOCK
Project.unit<0>.dataChannel<2>=gbtExmplDsgn gbtBankRst MGT_RXRESET_O
Project.unit<0>.dataChannel<3>=gbtExmplDsgn gbtBankRst GBT_RXRESET_O
Project.unit<0>.dataChannel<4>=gbtExmplDsgn gbtBankRst MGT_TXRESET_O
Project.unit<0>.dataChannel<5>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i CPLLLOCK
Project.unit<0>.dataChannel<6>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i CPLLREFCLKLOST
Project.unit<0>.dataChannel<7>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i CPLL_RESET
Project.unit<0>.dataChannel<8>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i GTTXRESET
Project.unit<0>.dataChannel<9>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i PHALIGNMENT_DONE
Project.unit<0>.dataDepth=1024
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=30
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=rst RESET_O
Project.unit<0>.triggerChannel<0><10>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i QPLL_RESET
Project.unit<0>.triggerChannel<0><11>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i SOFT_RESET
Project.unit<0>.triggerChannel<0><12>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i STABLE_CLOCK
Project.unit<0>.triggerChannel<0><13>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i TXRESETDONE
Project.unit<0>.triggerChannel<0><14>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i TXUSERCLK
Project.unit<0>.triggerChannel<0><15>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i TXUSERRDY
Project.unit<0>.triggerChannel<0><16>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i CPLLLOCK
Project.unit<0>.triggerChannel<0><17>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i CPLLREFCLKLOST
Project.unit<0>.triggerChannel<0><18>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i GTRXRESET
Project.unit<0>.triggerChannel<0><19>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i PHALIGNMENT_DONE
Project.unit<0>.triggerChannel<0><1>=gbtExmplDsgn gbtBankRst GBT_TXRESET_O
Project.unit<0>.triggerChannel<0><20>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i RECCLK_STABLE
Project.unit<0>.triggerChannel<0><21>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i RXDFEAGCHOLD
Project.unit<0>.triggerChannel<0><22>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i RXDFEAGCHOLD_glue_set
Project.unit<0>.triggerChannel<0><23>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i RXLPMHFHOLD
Project.unit<0>.triggerChannel<0><24>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i RXRESETDONE
Project.unit<0>.triggerChannel<0><25>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i RXUSERCLK
Project.unit<0>.triggerChannel<0><26>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i RXUSERRDY
Project.unit<0>.triggerChannel<0><27>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i SOFT_RESET
Project.unit<0>.triggerChannel<0><28>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i STABLE_CLOCK
Project.unit<0>.triggerChannel<0><29>=gbtExmplDsgn txPll LOCKED
Project.unit<0>.triggerChannel<0><2>=gbtExmplDsgn gbtBankRst MGT_RXRESET_O
Project.unit<0>.triggerChannel<0><30>=gbtExmplDsgn RX_FRAMECLK_ALIGNED_O
Project.unit<0>.triggerChannel<0><3>=gbtExmplDsgn gbtBankRst GBT_RXRESET_O
Project.unit<0>.triggerChannel<0><4>=gbtExmplDsgn gbtBankRst MGT_TXRESET_O
Project.unit<0>.triggerChannel<0><5>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i CPLLLOCK
Project.unit<0>.triggerChannel<0><6>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i CPLLREFCLKLOST
Project.unit<0>.triggerChannel<0><7>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i CPLL_RESET
Project.unit<0>.triggerChannel<0><8>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i GTTXRESET
Project.unit<0>.triggerChannel<0><9>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i PHALIGNMENT_DONE
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerPortCount=1
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortWidth<0>=30
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
