config latoptimized_measurements_altera_avalon_st_adapter_151_f4k6yuq_cfg;
		design latoptimized_measurements_altera_avalon_st_adapter_151_f4k6yuq;
		instance latoptimized_measurements_altera_avalon_st_adapter_151_f4k6yuq.error_adapter_0 use latoptimized_measurements_error_adapter_151.latoptimized_measurements_error_adapter_151_pcn7cty;
endconfig

