# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k325tffg900-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/kc705/vivado_project/kc705_gbt_example_design.cache/wt [current_project]
set_property parent.project_path D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/kc705/vivado_project/kc705_gbt_example_design.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kc705:part0:1.2 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/kc705/vivado_project/kc705_gbt_example_design.runs/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm_synth_1/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm.dcp
set_property used_in_implementation false [get_files D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/kc705/vivado_project/kc705_gbt_example_design.runs/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm_synth_1/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm.dcp]
add_files -quiet D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/kc705/vivado_project/kc705_gbt_example_design.runs/xlx_k7v7_tx_dpram_synth_1/xlx_k7v7_tx_dpram.dcp
set_property used_in_implementation false [get_files D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/kc705/vivado_project/kc705_gbt_example_design.runs/xlx_k7v7_tx_dpram_synth_1/xlx_k7v7_tx_dpram.dcp]
add_files -quiet D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/kc705/vivado_project/kc705_gbt_example_design.runs/xlx_k7v7_rx_dpram_synth_1/xlx_k7v7_rx_dpram.dcp
set_property used_in_implementation false [get_files D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/kc705/vivado_project/kc705_gbt_example_design.runs/xlx_k7v7_rx_dpram_synth_1/xlx_k7v7_rx_dpram.dcp]
add_files -quiet D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/kc705/vivado_project/kc705_gbt_example_design.runs/xlx_k7v7_tx_pll_synth_1/xlx_k7v7_tx_pll.dcp
set_property used_in_implementation false [get_files D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/kc705/vivado_project/kc705_gbt_example_design.runs/xlx_k7v7_tx_pll_synth_1/xlx_k7v7_tx_pll.dcp]
add_files -quiet D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/kc705/vivado_project/kc705_gbt_example_design.runs/xlx_k7v7_vivado_debug_synth_1/xlx_k7v7_vivado_debug.dcp
set_property used_in_implementation false [get_files D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/kc705/vivado_project/kc705_gbt_example_design.runs/xlx_k7v7_vivado_debug_synth_1/xlx_k7v7_vivado_debug.dcp]
add_files -quiet D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/kc705/vivado_project/kc705_gbt_example_design.runs/xlx_k7v7_vio_synth_1/xlx_k7v7_vio.dcp
set_property used_in_implementation false [get_files D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/kc705/vivado_project/kc705_gbt_example_design.runs/xlx_k7v7_vio_synth_1/xlx_k7v7_vio.dcp]
read_vhdl -library xil_defaultlib {
  D:/GBT-FPGA/trunk/gbt_bank/xilinx_k7v7/xlx_k7v7_gbt_bank_package.vhd
  D:/GBT-FPGA/trunk/gbt_bank/xilinx_k7v7/xlx_k7v7_gbt_banks_user_setup.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_bank_package.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_elpeval.vhd
  D:/GBT-FPGA/trunk/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_gtx_sync_pulse.vhd
  D:/GBT-FPGA/trunk/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_gtx_sync_block.vhd
  D:/GBT-FPGA/trunk/gbt_bank/xilinx_k7v7/gbt_tx/xlx_k7v7_gbt_tx_gearbox_std_dpram.vhd
  D:/GBT-FPGA/trunk/gbt_bank/xilinx_k7v7/gbt_rx/xlx_k7v7_gbt_rx_gearbox_std_dpram.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox_std_rdwrctrl.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_polydiv.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_rx/gbt_rx_gearbox_std_rdctrl.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_syndrom.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_rs2errcor.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_lmbddet.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_errlcpoly.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_chnsrch.vhd
  D:/GBT-FPGA/trunk/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_gtx_tx_startup_fsm.vhd
  D:/GBT-FPGA/trunk/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_gtx_tx_manual_phase_align.vhd
  D:/GBT-FPGA/trunk/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_gtx_std.vhd
  D:/GBT-FPGA/trunk/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_gtx_rx_startup_fsm.vhd
  D:/GBT-FPGA/trunk/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_gtx_rx_manual_phase_align.vhd
  D:/GBT-FPGA/trunk/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_gtx_latopt.vhd
  D:/GBT-FPGA/trunk/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_gtx_auto_phase_align.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/mgt/mgt_latopt_bitslipctrl.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_tx/gbt_tx_scrambler_21bit.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_tx/gbt_tx_scrambler_16bit.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox_std.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox_latopt.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_rsencode.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_intlver.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_rx/gbt_rx_gearbox_std.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_rx/gbt_rx_gearbox_latopt.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner_wraddr.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner_rightshift.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner_pattsearch.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner_bscounter.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_rx/gbt_rx_descrambler_21bit.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_rx/gbt_rx_descrambler_16bit.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_rsdec.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_deintlver.vhd
  D:/GBT-FPGA/trunk/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_mgt_std.vhd
  D:/GBT-FPGA/trunk/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_mgt_latopt.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_tx/gbt_tx_scrambler.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox_phasemon.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_tx/gbt_tx_encoder.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_rx/gbt_rx_status.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_rx/gbt_rx_gearbox.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_rx/gbt_rx_descrambler.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder.vhd
  D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/core_sources/gbt_rx_frameclk_phalgnr/xlx_k7v7_phalgnr_std_mmcm.vhd
  D:/GBT-FPGA/trunk/example_designs/core_sources/rxframeclk_phalgnr/phaligner_phase_computing.vhd
  D:/GBT-FPGA/trunk/example_designs/core_sources/rxframeclk_phalgnr/phaligner_phase_comparator.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/mgt/multi_gigabit_transceivers.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_tx/gbt_tx.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_rx/gbt_rx.vhd
  D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/core_sources/gbt_rx_frameclk_phalgnr/phaligner_mmcm_controller.vhd
  D:/GBT-FPGA/trunk/example_designs/core_sources/rxframeclk_phalgnr/gbt_rx_frameclk_phalgnr.vhd
  D:/GBT-FPGA/trunk/example_designs/core_sources/gbt_pattern_matchflag.vhd
  D:/GBT-FPGA/trunk/example_designs/core_sources/gbt_pattern_generator.vhd
  D:/GBT-FPGA/trunk/example_designs/core_sources/gbt_pattern_checker.vhd
  D:/GBT-FPGA/trunk/example_designs/core_sources/gbt_bank_reset.vhd
  D:/GBT-FPGA/trunk/gbt_bank/core_sources/gbt_bank.vhd
  D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/core_sources/xlx_k7v7_gbt_example_design.vhd
  D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/core_sources/xlx_k7v7_reset.vhd
  D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/kc705/vivado_kc705_gbt_example_design.vhd
}
read_xdc D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/kc705/xdc/kc705_exmpldsgn_floorplanning.xdc
set_property used_in_implementation false [get_files D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/kc705/xdc/kc705_exmpldsgn_floorplanning.xdc]

read_xdc D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/kc705/xdc/kc705_gbt_exmpldsgn_clks.xdc
set_property used_in_implementation false [get_files D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/kc705/xdc/kc705_gbt_exmpldsgn_clks.xdc]

read_xdc D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/kc705/xdc/kc705_gbt_exmpldsgn_io.xdc
set_property used_in_implementation false [get_files D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/kc705/xdc/kc705_gbt_exmpldsgn_io.xdc]

read_xdc D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/kc705/xdc/kc705_gbt_exmpldsn_timingclosure.xdc
set_property used_in_implementation false [get_files D:/GBT-FPGA/trunk/example_designs/xilinx_k7v7/kc705/xdc/kc705_gbt_exmpldsn_timingclosure.xdc]

synth_design -top kc705_gbt_example_design -part xc7k325tffg900-2
write_checkpoint -noxdef kc705_gbt_example_design.dcp
catch { report_utilization -file kc705_gbt_example_design_utilization_synth.rpt -pb kc705_gbt_example_design_utilization_synth.pb }
