#ChipScope Core Inserter Project File Version 3.0
#Tue Jan 07 23:54:06 CET 2014
Project.device.designInputFile=M\:\\project_gbt\\hdl_projects\\new_structure_20_40_xlx_7\\example_designs\\xilinx_k7v7\\kc705\\ise_project\\kc705_gbt_example_design_cs.ngc
Project.device.designOutputFile=M\:\\project_gbt\\hdl_projects\\new_structure_20_40_xlx_7\\example_designs\\xilinx_k7v7\\kc705\\ise_project\\kc705_gbt_example_design_cs.ngc
Project.device.deviceFamily=20
Project.device.enableRPMs=false
Project.device.outputDirectory=M\:\\project_gbt\\hdl_projects\\new_structure_20_40_xlx_7\\example_designs\\xilinx_k7v7\\kc705\\ise_project\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=3
Project.filter<0>=
Project.filter<1>=*TX*
Project.filter<2>=*
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=4
Project.unit<0>.clockChannel=gbtExmplDsgn TX_FRAMECLK_O
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataChannel<0>=gbtExmplDsgn TX_DATA_O<0>
Project.unit<0>.dataChannel<10>=gbtExmplDsgn TX_DATA_O<10>
Project.unit<0>.dataChannel<11>=gbtExmplDsgn TX_DATA_O<11>
Project.unit<0>.dataChannel<12>=gbtExmplDsgn TX_DATA_O<12>
Project.unit<0>.dataChannel<13>=gbtExmplDsgn TX_DATA_O<13>
Project.unit<0>.dataChannel<14>=gbtExmplDsgn TX_DATA_O<14>
Project.unit<0>.dataChannel<15>=gbtExmplDsgn TX_DATA_O<15>
Project.unit<0>.dataChannel<16>=gbtExmplDsgn TX_DATA_O<16>
Project.unit<0>.dataChannel<17>=gbtExmplDsgn TX_DATA_O<17>
Project.unit<0>.dataChannel<18>=gbtExmplDsgn TX_DATA_O<18>
Project.unit<0>.dataChannel<19>=gbtExmplDsgn TX_DATA_O<19>
Project.unit<0>.dataChannel<1>=gbtExmplDsgn TX_DATA_O<1>
Project.unit<0>.dataChannel<20>=gbtExmplDsgn TX_DATA_O<20>
Project.unit<0>.dataChannel<21>=gbtExmplDsgn TX_DATA_O<21>
Project.unit<0>.dataChannel<22>=gbtExmplDsgn TX_DATA_O<22>
Project.unit<0>.dataChannel<23>=gbtExmplDsgn TX_DATA_O<23>
Project.unit<0>.dataChannel<24>=gbtExmplDsgn TX_DATA_O<24>
Project.unit<0>.dataChannel<25>=gbtExmplDsgn TX_DATA_O<25>
Project.unit<0>.dataChannel<26>=gbtExmplDsgn TX_DATA_O<26>
Project.unit<0>.dataChannel<27>=gbtExmplDsgn TX_DATA_O<27>
Project.unit<0>.dataChannel<28>=gbtExmplDsgn TX_DATA_O<28>
Project.unit<0>.dataChannel<29>=gbtExmplDsgn TX_DATA_O<29>
Project.unit<0>.dataChannel<2>=gbtExmplDsgn TX_DATA_O<2>
Project.unit<0>.dataChannel<30>=gbtExmplDsgn TX_DATA_O<30>
Project.unit<0>.dataChannel<31>=gbtExmplDsgn TX_DATA_O<31>
Project.unit<0>.dataChannel<32>=gbtExmplDsgn TX_DATA_O<32>
Project.unit<0>.dataChannel<33>=gbtExmplDsgn TX_DATA_O<33>
Project.unit<0>.dataChannel<34>=gbtExmplDsgn TX_DATA_O<34>
Project.unit<0>.dataChannel<35>=gbtExmplDsgn TX_DATA_O<35>
Project.unit<0>.dataChannel<36>=gbtExmplDsgn TX_DATA_O<36>
Project.unit<0>.dataChannel<37>=gbtExmplDsgn TX_DATA_O<37>
Project.unit<0>.dataChannel<38>=gbtExmplDsgn TX_DATA_O<38>
Project.unit<0>.dataChannel<39>=gbtExmplDsgn TX_DATA_O<39>
Project.unit<0>.dataChannel<3>=gbtExmplDsgn TX_DATA_O<3>
Project.unit<0>.dataChannel<40>=gbtExmplDsgn TX_DATA_O<40>
Project.unit<0>.dataChannel<41>=gbtExmplDsgn TX_DATA_O<41>
Project.unit<0>.dataChannel<42>=gbtExmplDsgn TX_DATA_O<42>
Project.unit<0>.dataChannel<43>=gbtExmplDsgn TX_DATA_O<43>
Project.unit<0>.dataChannel<44>=gbtExmplDsgn TX_DATA_O<44>
Project.unit<0>.dataChannel<45>=gbtExmplDsgn TX_DATA_O<45>
Project.unit<0>.dataChannel<46>=gbtExmplDsgn TX_DATA_O<46>
Project.unit<0>.dataChannel<47>=gbtExmplDsgn TX_DATA_O<47>
Project.unit<0>.dataChannel<48>=gbtExmplDsgn TX_DATA_O<48>
Project.unit<0>.dataChannel<49>=gbtExmplDsgn TX_DATA_O<49>
Project.unit<0>.dataChannel<4>=gbtExmplDsgn TX_DATA_O<4>
Project.unit<0>.dataChannel<50>=gbtExmplDsgn TX_DATA_O<50>
Project.unit<0>.dataChannel<51>=gbtExmplDsgn TX_DATA_O<51>
Project.unit<0>.dataChannel<52>=gbtExmplDsgn TX_DATA_O<52>
Project.unit<0>.dataChannel<53>=gbtExmplDsgn TX_DATA_O<53>
Project.unit<0>.dataChannel<54>=gbtExmplDsgn TX_DATA_O<54>
Project.unit<0>.dataChannel<55>=gbtExmplDsgn TX_DATA_O<55>
Project.unit<0>.dataChannel<56>=gbtExmplDsgn TX_DATA_O<56>
Project.unit<0>.dataChannel<57>=gbtExmplDsgn TX_DATA_O<57>
Project.unit<0>.dataChannel<58>=gbtExmplDsgn TX_DATA_O<58>
Project.unit<0>.dataChannel<59>=gbtExmplDsgn TX_DATA_O<59>
Project.unit<0>.dataChannel<5>=gbtExmplDsgn TX_DATA_O<5>
Project.unit<0>.dataChannel<60>=gbtExmplDsgn TX_DATA_O<60>
Project.unit<0>.dataChannel<61>=gbtExmplDsgn TX_DATA_O<61>
Project.unit<0>.dataChannel<62>=gbtExmplDsgn TX_DATA_O<62>
Project.unit<0>.dataChannel<63>=gbtExmplDsgn TX_DATA_O<63>
Project.unit<0>.dataChannel<64>=gbtExmplDsgn TX_DATA_O<64>
Project.unit<0>.dataChannel<65>=gbtExmplDsgn TX_DATA_O<65>
Project.unit<0>.dataChannel<66>=gbtExmplDsgn TX_DATA_O<66>
Project.unit<0>.dataChannel<67>=gbtExmplDsgn TX_DATA_O<67>
Project.unit<0>.dataChannel<68>=gbtExmplDsgn TX_DATA_O<68>
Project.unit<0>.dataChannel<69>=gbtExmplDsgn TX_DATA_O<69>
Project.unit<0>.dataChannel<6>=gbtExmplDsgn TX_DATA_O<6>
Project.unit<0>.dataChannel<70>=gbtExmplDsgn TX_DATA_O<70>
Project.unit<0>.dataChannel<71>=gbtExmplDsgn TX_DATA_O<71>
Project.unit<0>.dataChannel<72>=gbtExmplDsgn TX_DATA_O<72>
Project.unit<0>.dataChannel<73>=gbtExmplDsgn TX_DATA_O<73>
Project.unit<0>.dataChannel<74>=gbtExmplDsgn TX_DATA_O<74>
Project.unit<0>.dataChannel<75>=gbtExmplDsgn TX_DATA_O<75>
Project.unit<0>.dataChannel<76>=gbtExmplDsgn TX_DATA_O<76>
Project.unit<0>.dataChannel<77>=gbtExmplDsgn TX_DATA_O<77>
Project.unit<0>.dataChannel<78>=gbtExmplDsgn TX_DATA_O<78>
Project.unit<0>.dataChannel<79>=gbtExmplDsgn TX_DATA_O<79>
Project.unit<0>.dataChannel<7>=gbtExmplDsgn TX_DATA_O<7>
Project.unit<0>.dataChannel<80>=gbtExmplDsgn TX_DATA_O<80>
Project.unit<0>.dataChannel<81>=gbtExmplDsgn TX_DATA_O<81>
Project.unit<0>.dataChannel<82>=gbtExmplDsgn TX_DATA_O<82>
Project.unit<0>.dataChannel<83>=gbtExmplDsgn TX_DATA_O<83>
Project.unit<0>.dataChannel<84>=gbtExmplDsgn COMMONDATA_ERROR_SEEN_FLAG_O
Project.unit<0>.dataChannel<85>=gbtExmplDsgn TX_MATCHFLAG_O
Project.unit<0>.dataChannel<86>=gbtExmplDsgn MGT_READY_O
Project.unit<0>.dataChannel<8>=gbtExmplDsgn TX_DATA_O<8>
Project.unit<0>.dataChannel<9>=gbtExmplDsgn TX_DATA_O<9>
Project.unit<0>.dataDepth=1024
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=87
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=gbtExmplDsgn TX_DATA_O<0>
Project.unit<0>.triggerChannel<0><10>=gbtExmplDsgn TX_DATA_O<10>
Project.unit<0>.triggerChannel<0><11>=gbtExmplDsgn TX_DATA_O<11>
Project.unit<0>.triggerChannel<0><12>=gbtExmplDsgn TX_DATA_O<12>
Project.unit<0>.triggerChannel<0><13>=gbtExmplDsgn TX_DATA_O<13>
Project.unit<0>.triggerChannel<0><14>=gbtExmplDsgn TX_DATA_O<14>
Project.unit<0>.triggerChannel<0><15>=gbtExmplDsgn TX_DATA_O<15>
Project.unit<0>.triggerChannel<0><16>=gbtExmplDsgn TX_DATA_O<16>
Project.unit<0>.triggerChannel<0><17>=gbtExmplDsgn TX_DATA_O<17>
Project.unit<0>.triggerChannel<0><18>=gbtExmplDsgn TX_DATA_O<18>
Project.unit<0>.triggerChannel<0><19>=gbtExmplDsgn TX_DATA_O<19>
Project.unit<0>.triggerChannel<0><1>=gbtExmplDsgn TX_DATA_O<1>
Project.unit<0>.triggerChannel<0><20>=gbtExmplDsgn TX_DATA_O<20>
Project.unit<0>.triggerChannel<0><21>=gbtExmplDsgn TX_DATA_O<21>
Project.unit<0>.triggerChannel<0><22>=gbtExmplDsgn TX_DATA_O<22>
Project.unit<0>.triggerChannel<0><23>=gbtExmplDsgn TX_DATA_O<23>
Project.unit<0>.triggerChannel<0><24>=gbtExmplDsgn TX_DATA_O<24>
Project.unit<0>.triggerChannel<0><25>=gbtExmplDsgn TX_DATA_O<25>
Project.unit<0>.triggerChannel<0><26>=gbtExmplDsgn TX_DATA_O<26>
Project.unit<0>.triggerChannel<0><27>=gbtExmplDsgn TX_DATA_O<27>
Project.unit<0>.triggerChannel<0><28>=gbtExmplDsgn TX_DATA_O<28>
Project.unit<0>.triggerChannel<0><29>=gbtExmplDsgn TX_DATA_O<29>
Project.unit<0>.triggerChannel<0><2>=gbtExmplDsgn TX_DATA_O<2>
Project.unit<0>.triggerChannel<0><30>=gbtExmplDsgn TX_DATA_O<30>
Project.unit<0>.triggerChannel<0><31>=gbtExmplDsgn TX_DATA_O<31>
Project.unit<0>.triggerChannel<0><32>=gbtExmplDsgn TX_DATA_O<32>
Project.unit<0>.triggerChannel<0><33>=gbtExmplDsgn TX_DATA_O<33>
Project.unit<0>.triggerChannel<0><34>=gbtExmplDsgn TX_DATA_O<34>
Project.unit<0>.triggerChannel<0><35>=gbtExmplDsgn TX_DATA_O<35>
Project.unit<0>.triggerChannel<0><36>=gbtExmplDsgn TX_DATA_O<36>
Project.unit<0>.triggerChannel<0><37>=gbtExmplDsgn TX_DATA_O<37>
Project.unit<0>.triggerChannel<0><38>=gbtExmplDsgn TX_DATA_O<38>
Project.unit<0>.triggerChannel<0><39>=gbtExmplDsgn TX_DATA_O<39>
Project.unit<0>.triggerChannel<0><3>=gbtExmplDsgn TX_DATA_O<3>
Project.unit<0>.triggerChannel<0><40>=gbtExmplDsgn TX_DATA_O<40>
Project.unit<0>.triggerChannel<0><41>=gbtExmplDsgn TX_DATA_O<41>
Project.unit<0>.triggerChannel<0><42>=gbtExmplDsgn TX_DATA_O<42>
Project.unit<0>.triggerChannel<0><43>=gbtExmplDsgn TX_DATA_O<43>
Project.unit<0>.triggerChannel<0><44>=gbtExmplDsgn TX_DATA_O<44>
Project.unit<0>.triggerChannel<0><45>=gbtExmplDsgn TX_DATA_O<45>
Project.unit<0>.triggerChannel<0><46>=gbtExmplDsgn TX_DATA_O<46>
Project.unit<0>.triggerChannel<0><47>=gbtExmplDsgn TX_DATA_O<47>
Project.unit<0>.triggerChannel<0><48>=gbtExmplDsgn TX_DATA_O<48>
Project.unit<0>.triggerChannel<0><49>=gbtExmplDsgn TX_DATA_O<49>
Project.unit<0>.triggerChannel<0><4>=gbtExmplDsgn TX_DATA_O<4>
Project.unit<0>.triggerChannel<0><50>=gbtExmplDsgn TX_DATA_O<50>
Project.unit<0>.triggerChannel<0><51>=gbtExmplDsgn TX_DATA_O<51>
Project.unit<0>.triggerChannel<0><52>=gbtExmplDsgn TX_DATA_O<52>
Project.unit<0>.triggerChannel<0><53>=gbtExmplDsgn TX_DATA_O<53>
Project.unit<0>.triggerChannel<0><54>=gbtExmplDsgn TX_DATA_O<54>
Project.unit<0>.triggerChannel<0><55>=gbtExmplDsgn TX_DATA_O<55>
Project.unit<0>.triggerChannel<0><56>=gbtExmplDsgn TX_DATA_O<56>
Project.unit<0>.triggerChannel<0><57>=gbtExmplDsgn TX_DATA_O<57>
Project.unit<0>.triggerChannel<0><58>=gbtExmplDsgn TX_DATA_O<58>
Project.unit<0>.triggerChannel<0><59>=gbtExmplDsgn TX_DATA_O<59>
Project.unit<0>.triggerChannel<0><5>=gbtExmplDsgn TX_DATA_O<5>
Project.unit<0>.triggerChannel<0><60>=gbtExmplDsgn TX_DATA_O<60>
Project.unit<0>.triggerChannel<0><61>=gbtExmplDsgn TX_DATA_O<61>
Project.unit<0>.triggerChannel<0><62>=gbtExmplDsgn TX_DATA_O<62>
Project.unit<0>.triggerChannel<0><63>=gbtExmplDsgn TX_DATA_O<63>
Project.unit<0>.triggerChannel<0><64>=gbtExmplDsgn TX_DATA_O<64>
Project.unit<0>.triggerChannel<0><65>=gbtExmplDsgn TX_DATA_O<65>
Project.unit<0>.triggerChannel<0><66>=gbtExmplDsgn TX_DATA_O<66>
Project.unit<0>.triggerChannel<0><67>=gbtExmplDsgn TX_DATA_O<67>
Project.unit<0>.triggerChannel<0><68>=gbtExmplDsgn TX_DATA_O<68>
Project.unit<0>.triggerChannel<0><69>=gbtExmplDsgn TX_DATA_O<69>
Project.unit<0>.triggerChannel<0><6>=gbtExmplDsgn TX_DATA_O<6>
Project.unit<0>.triggerChannel<0><70>=gbtExmplDsgn TX_DATA_O<70>
Project.unit<0>.triggerChannel<0><71>=gbtExmplDsgn TX_DATA_O<71>
Project.unit<0>.triggerChannel<0><72>=gbtExmplDsgn TX_DATA_O<72>
Project.unit<0>.triggerChannel<0><73>=gbtExmplDsgn TX_DATA_O<73>
Project.unit<0>.triggerChannel<0><74>=gbtExmplDsgn TX_DATA_O<74>
Project.unit<0>.triggerChannel<0><75>=gbtExmplDsgn TX_DATA_O<75>
Project.unit<0>.triggerChannel<0><76>=gbtExmplDsgn TX_DATA_O<76>
Project.unit<0>.triggerChannel<0><77>=gbtExmplDsgn TX_DATA_O<77>
Project.unit<0>.triggerChannel<0><78>=gbtExmplDsgn TX_DATA_O<78>
Project.unit<0>.triggerChannel<0><79>=gbtExmplDsgn TX_DATA_O<79>
Project.unit<0>.triggerChannel<0><7>=gbtExmplDsgn TX_DATA_O<7>
Project.unit<0>.triggerChannel<0><80>=gbtExmplDsgn TX_DATA_O<80>
Project.unit<0>.triggerChannel<0><81>=gbtExmplDsgn TX_DATA_O<81>
Project.unit<0>.triggerChannel<0><82>=gbtExmplDsgn TX_DATA_O<82>
Project.unit<0>.triggerChannel<0><83>=gbtExmplDsgn TX_DATA_O<83>
Project.unit<0>.triggerChannel<0><8>=gbtExmplDsgn TX_DATA_O<8>
Project.unit<0>.triggerChannel<0><9>=gbtExmplDsgn TX_DATA_O<9>
Project.unit<0>.triggerChannel<1><0>=gbtExmplDsgn COMMONDATA_ERROR_SEEN_FLAG_O
Project.unit<0>.triggerChannel<1><1>=gbtExmplDsgn TX_MATCHFLAG_O
Project.unit<0>.triggerChannel<1><2>=gbtExmplDsgn MGT_READY_O
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerPortCount=2
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortWidth<0>=84
Project.unit<0>.triggerPortWidth<1>=3
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
Project.unit<1>.clockChannel=gbtExmplDsgn TX_WORDCLK_O
Project.unit<1>.clockEdge=Rising
Project.unit<1>.dataChannel<0>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><0>
Project.unit<1>.dataChannel<10>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><10>
Project.unit<1>.dataChannel<11>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><11>
Project.unit<1>.dataChannel<12>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><12>
Project.unit<1>.dataChannel<13>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><13>
Project.unit<1>.dataChannel<14>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><14>
Project.unit<1>.dataChannel<15>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><15>
Project.unit<1>.dataChannel<16>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><16>
Project.unit<1>.dataChannel<17>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><17>
Project.unit<1>.dataChannel<18>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><18>
Project.unit<1>.dataChannel<19>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><19>
Project.unit<1>.dataChannel<1>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><1>
Project.unit<1>.dataChannel<20>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><20>
Project.unit<1>.dataChannel<21>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><21>
Project.unit<1>.dataChannel<22>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><22>
Project.unit<1>.dataChannel<23>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><23>
Project.unit<1>.dataChannel<24>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><24>
Project.unit<1>.dataChannel<25>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><25>
Project.unit<1>.dataChannel<26>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><26>
Project.unit<1>.dataChannel<27>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><27>
Project.unit<1>.dataChannel<28>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><28>
Project.unit<1>.dataChannel<29>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><29>
Project.unit<1>.dataChannel<2>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><2>
Project.unit<1>.dataChannel<30>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><30>
Project.unit<1>.dataChannel<31>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><31>
Project.unit<1>.dataChannel<32>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><32>
Project.unit<1>.dataChannel<33>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><33>
Project.unit<1>.dataChannel<34>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><34>
Project.unit<1>.dataChannel<35>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><35>
Project.unit<1>.dataChannel<36>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><36>
Project.unit<1>.dataChannel<37>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><37>
Project.unit<1>.dataChannel<38>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><38>
Project.unit<1>.dataChannel<39>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><39>
Project.unit<1>.dataChannel<3>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><3>
Project.unit<1>.dataChannel<4>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><4>
Project.unit<1>.dataChannel<5>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><5>
Project.unit<1>.dataChannel<6>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><6>
Project.unit<1>.dataChannel<7>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><7>
Project.unit<1>.dataChannel<8>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><8>
Project.unit<1>.dataChannel<9>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><9>
Project.unit<1>.dataDepth=1024
Project.unit<1>.dataEqualsTrigger=true
Project.unit<1>.dataPortWidth=40
Project.unit<1>.enableGaps=false
Project.unit<1>.enableStorageQualification=true
Project.unit<1>.enableTimestamps=false
Project.unit<1>.timestampDepth=0
Project.unit<1>.timestampWidth=0
Project.unit<1>.triggerChannel<0><0>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><0>
Project.unit<1>.triggerChannel<0><10>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><10>
Project.unit<1>.triggerChannel<0><11>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><11>
Project.unit<1>.triggerChannel<0><12>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><12>
Project.unit<1>.triggerChannel<0><13>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><13>
Project.unit<1>.triggerChannel<0><14>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><14>
Project.unit<1>.triggerChannel<0><15>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><15>
Project.unit<1>.triggerChannel<0><16>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><16>
Project.unit<1>.triggerChannel<0><17>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><17>
Project.unit<1>.triggerChannel<0><18>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><18>
Project.unit<1>.triggerChannel<0><19>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><19>
Project.unit<1>.triggerChannel<0><1>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><1>
Project.unit<1>.triggerChannel<0><20>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><20>
Project.unit<1>.triggerChannel<0><21>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><21>
Project.unit<1>.triggerChannel<0><22>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><22>
Project.unit<1>.triggerChannel<0><23>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><23>
Project.unit<1>.triggerChannel<0><24>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><24>
Project.unit<1>.triggerChannel<0><25>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><25>
Project.unit<1>.triggerChannel<0><26>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><26>
Project.unit<1>.triggerChannel<0><27>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><27>
Project.unit<1>.triggerChannel<0><28>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><28>
Project.unit<1>.triggerChannel<0><29>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><29>
Project.unit<1>.triggerChannel<0><2>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><2>
Project.unit<1>.triggerChannel<0><30>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><30>
Project.unit<1>.triggerChannel<0><31>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><31>
Project.unit<1>.triggerChannel<0><32>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><32>
Project.unit<1>.triggerChannel<0><33>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><33>
Project.unit<1>.triggerChannel<0><34>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><34>
Project.unit<1>.triggerChannel<0><35>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><35>
Project.unit<1>.triggerChannel<0><36>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><36>
Project.unit<1>.triggerChannel<0><37>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><37>
Project.unit<1>.triggerChannel<0><38>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><38>
Project.unit<1>.triggerChannel<0><39>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><39>
Project.unit<1>.triggerChannel<0><3>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><3>
Project.unit<1>.triggerChannel<0><4>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><4>
Project.unit<1>.triggerChannel<0><5>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><5>
Project.unit<1>.triggerChannel<0><6>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><6>
Project.unit<1>.triggerChannel<0><7>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><7>
Project.unit<1>.triggerChannel<0><8>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><8>
Project.unit<1>.triggerChannel<0><9>=gbtExmplDsgn gbtBank_1 mgt GBT_TX_WORD_I<1><9>
Project.unit<1>.triggerConditionCountWidth=0
Project.unit<1>.triggerMatchCount<0>=1
Project.unit<1>.triggerMatchCountWidth<0><0>=0
Project.unit<1>.triggerMatchType<0><0>=1
Project.unit<1>.triggerPortCount=1
Project.unit<1>.triggerPortIsData<0>=true
Project.unit<1>.triggerPortWidth<0>=40
Project.unit<1>.triggerSequencerLevels=16
Project.unit<1>.triggerSequencerType=1
Project.unit<1>.type=ilapro
Project.unit<2>.clockChannel=gbtExmplDsgn RX_WORDCLK_O
Project.unit<2>.clockEdge=Rising
Project.unit<2>.dataChannel<0>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><0>
Project.unit<2>.dataChannel<10>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><10>
Project.unit<2>.dataChannel<11>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><11>
Project.unit<2>.dataChannel<12>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><12>
Project.unit<2>.dataChannel<13>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><13>
Project.unit<2>.dataChannel<14>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><14>
Project.unit<2>.dataChannel<15>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><15>
Project.unit<2>.dataChannel<16>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><16>
Project.unit<2>.dataChannel<17>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><17>
Project.unit<2>.dataChannel<18>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><18>
Project.unit<2>.dataChannel<19>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><19>
Project.unit<2>.dataChannel<1>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><1>
Project.unit<2>.dataChannel<20>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><20>
Project.unit<2>.dataChannel<21>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><21>
Project.unit<2>.dataChannel<22>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><22>
Project.unit<2>.dataChannel<23>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><23>
Project.unit<2>.dataChannel<24>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><24>
Project.unit<2>.dataChannel<25>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><25>
Project.unit<2>.dataChannel<26>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><26>
Project.unit<2>.dataChannel<27>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><27>
Project.unit<2>.dataChannel<28>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><28>
Project.unit<2>.dataChannel<29>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><29>
Project.unit<2>.dataChannel<2>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><2>
Project.unit<2>.dataChannel<30>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><30>
Project.unit<2>.dataChannel<31>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><31>
Project.unit<2>.dataChannel<32>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><32>
Project.unit<2>.dataChannel<33>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><33>
Project.unit<2>.dataChannel<34>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><34>
Project.unit<2>.dataChannel<35>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><35>
Project.unit<2>.dataChannel<36>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><36>
Project.unit<2>.dataChannel<37>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><37>
Project.unit<2>.dataChannel<38>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><38>
Project.unit<2>.dataChannel<39>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><39>
Project.unit<2>.dataChannel<3>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><3>
Project.unit<2>.dataChannel<40>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i RXRESETDONE
Project.unit<2>.dataChannel<41>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i TXRESETDONE
Project.unit<2>.dataChannel<42>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<0>
Project.unit<2>.dataChannel<43>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<1>
Project.unit<2>.dataChannel<44>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<2>
Project.unit<2>.dataChannel<45>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<3>
Project.unit<2>.dataChannel<46>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<4>
Project.unit<2>.dataChannel<47>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<5>
Project.unit<2>.dataChannel<48>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<6>
Project.unit<2>.dataChannel<49>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<7>
Project.unit<2>.dataChannel<4>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><4>
Project.unit<2>.dataChannel<50>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<8>
Project.unit<2>.dataChannel<51>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<9>
Project.unit<2>.dataChannel<52>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<10>
Project.unit<2>.dataChannel<53>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<11>
Project.unit<2>.dataChannel<54>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<12>
Project.unit<2>.dataChannel<55>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<13>
Project.unit<2>.dataChannel<56>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<14>
Project.unit<2>.dataChannel<57>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<15>
Project.unit<2>.dataChannel<58>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<16>
Project.unit<2>.dataChannel<59>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<17>
Project.unit<2>.dataChannel<5>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><5>
Project.unit<2>.dataChannel<60>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<18>
Project.unit<2>.dataChannel<61>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<19>
Project.unit<2>.dataChannel<62>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<20>
Project.unit<2>.dataChannel<63>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<21>
Project.unit<2>.dataChannel<64>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<22>
Project.unit<2>.dataChannel<65>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<23>
Project.unit<2>.dataChannel<66>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<24>
Project.unit<2>.dataChannel<67>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<25>
Project.unit<2>.dataChannel<68>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<26>
Project.unit<2>.dataChannel<69>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<27>
Project.unit<2>.dataChannel<6>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><6>
Project.unit<2>.dataChannel<70>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<28>
Project.unit<2>.dataChannel<71>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<29>
Project.unit<2>.dataChannel<72>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<30>
Project.unit<2>.dataChannel<73>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<31>
Project.unit<2>.dataChannel<74>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<32>
Project.unit<2>.dataChannel<75>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<33>
Project.unit<2>.dataChannel<76>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<34>
Project.unit<2>.dataChannel<77>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<35>
Project.unit<2>.dataChannel<78>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<36>
Project.unit<2>.dataChannel<79>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<37>
Project.unit<2>.dataChannel<7>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><7>
Project.unit<2>.dataChannel<80>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<38>
Project.unit<2>.dataChannel<81>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<39>
Project.unit<2>.dataChannel<8>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><8>
Project.unit<2>.dataChannel<9>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><9>
Project.unit<2>.dataDepth=1024
Project.unit<2>.dataEqualsTrigger=true
Project.unit<2>.dataPortWidth=82
Project.unit<2>.enableGaps=false
Project.unit<2>.enableStorageQualification=true
Project.unit<2>.enableTimestamps=false
Project.unit<2>.timestampDepth=0
Project.unit<2>.timestampWidth=0
Project.unit<2>.triggerChannel<0><0>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><0>
Project.unit<2>.triggerChannel<0><10>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><10>
Project.unit<2>.triggerChannel<0><11>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><11>
Project.unit<2>.triggerChannel<0><12>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><12>
Project.unit<2>.triggerChannel<0><13>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><13>
Project.unit<2>.triggerChannel<0><14>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><14>
Project.unit<2>.triggerChannel<0><15>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><15>
Project.unit<2>.triggerChannel<0><16>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><16>
Project.unit<2>.triggerChannel<0><17>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><17>
Project.unit<2>.triggerChannel<0><18>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><18>
Project.unit<2>.triggerChannel<0><19>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><19>
Project.unit<2>.triggerChannel<0><1>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><1>
Project.unit<2>.triggerChannel<0><20>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><20>
Project.unit<2>.triggerChannel<0><21>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><21>
Project.unit<2>.triggerChannel<0><22>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><22>
Project.unit<2>.triggerChannel<0><23>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><23>
Project.unit<2>.triggerChannel<0><24>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><24>
Project.unit<2>.triggerChannel<0><25>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><25>
Project.unit<2>.triggerChannel<0><26>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><26>
Project.unit<2>.triggerChannel<0><27>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><27>
Project.unit<2>.triggerChannel<0><28>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><28>
Project.unit<2>.triggerChannel<0><29>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><29>
Project.unit<2>.triggerChannel<0><2>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><2>
Project.unit<2>.triggerChannel<0><30>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><30>
Project.unit<2>.triggerChannel<0><31>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><31>
Project.unit<2>.triggerChannel<0><32>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><32>
Project.unit<2>.triggerChannel<0><33>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><33>
Project.unit<2>.triggerChannel<0><34>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><34>
Project.unit<2>.triggerChannel<0><35>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><35>
Project.unit<2>.triggerChannel<0><36>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><36>
Project.unit<2>.triggerChannel<0><37>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><37>
Project.unit<2>.triggerChannel<0><38>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><38>
Project.unit<2>.triggerChannel<0><39>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><39>
Project.unit<2>.triggerChannel<0><3>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><3>
Project.unit<2>.triggerChannel<0><4>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><4>
Project.unit<2>.triggerChannel<0><5>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><5>
Project.unit<2>.triggerChannel<0><6>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><6>
Project.unit<2>.triggerChannel<0><7>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><7>
Project.unit<2>.triggerChannel<0><8>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><8>
Project.unit<2>.triggerChannel<0><9>=gbtExmplDsgn gbtBank_1 mgt GBT_RX_WORD_O<1><9>
Project.unit<2>.triggerChannel<1><0>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i RXRESETDONE
Project.unit<2>.triggerChannel<1><1>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i TXRESETDONE
Project.unit<2>.triggerChannel<2><0>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<0>
Project.unit<2>.triggerChannel<2><10>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<10>
Project.unit<2>.triggerChannel<2><11>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<11>
Project.unit<2>.triggerChannel<2><12>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<12>
Project.unit<2>.triggerChannel<2><13>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<13>
Project.unit<2>.triggerChannel<2><14>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<14>
Project.unit<2>.triggerChannel<2><15>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<15>
Project.unit<2>.triggerChannel<2><16>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<16>
Project.unit<2>.triggerChannel<2><17>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<17>
Project.unit<2>.triggerChannel<2><18>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<18>
Project.unit<2>.triggerChannel<2><19>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<19>
Project.unit<2>.triggerChannel<2><1>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<1>
Project.unit<2>.triggerChannel<2><20>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<20>
Project.unit<2>.triggerChannel<2><21>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<21>
Project.unit<2>.triggerChannel<2><22>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<22>
Project.unit<2>.triggerChannel<2><23>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<23>
Project.unit<2>.triggerChannel<2><24>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<24>
Project.unit<2>.triggerChannel<2><25>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<25>
Project.unit<2>.triggerChannel<2><26>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<26>
Project.unit<2>.triggerChannel<2><27>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<27>
Project.unit<2>.triggerChannel<2><28>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<28>
Project.unit<2>.triggerChannel<2><29>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<29>
Project.unit<2>.triggerChannel<2><2>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<2>
Project.unit<2>.triggerChannel<2><30>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<30>
Project.unit<2>.triggerChannel<2><31>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<31>
Project.unit<2>.triggerChannel<2><32>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<32>
Project.unit<2>.triggerChannel<2><33>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<33>
Project.unit<2>.triggerChannel<2><34>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<34>
Project.unit<2>.triggerChannel<2><35>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<35>
Project.unit<2>.triggerChannel<2><36>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<36>
Project.unit<2>.triggerChannel<2><37>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<37>
Project.unit<2>.triggerChannel<2><38>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<38>
Project.unit<2>.triggerChannel<2><39>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<39>
Project.unit<2>.triggerChannel<2><3>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<3>
Project.unit<2>.triggerChannel<2><4>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<4>
Project.unit<2>.triggerChannel<2><5>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<5>
Project.unit<2>.triggerChannel<2><6>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<6>
Project.unit<2>.triggerChannel<2><7>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<7>
Project.unit<2>.triggerChannel<2><8>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<8>
Project.unit<2>.triggerChannel<2><9>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx frameAligner shiftedRxWord_from_rightShifter<9>
Project.unit<2>.triggerConditionCountWidth=0
Project.unit<2>.triggerMatchCount<0>=1
Project.unit<2>.triggerMatchCount<1>=1
Project.unit<2>.triggerMatchCount<2>=1
Project.unit<2>.triggerMatchCountWidth<0><0>=0
Project.unit<2>.triggerMatchCountWidth<1><0>=0
Project.unit<2>.triggerMatchCountWidth<2><0>=0
Project.unit<2>.triggerMatchType<0><0>=1
Project.unit<2>.triggerMatchType<1><0>=1
Project.unit<2>.triggerMatchType<2><0>=1
Project.unit<2>.triggerPortCount=3
Project.unit<2>.triggerPortIsData<0>=true
Project.unit<2>.triggerPortIsData<1>=true
Project.unit<2>.triggerPortIsData<2>=true
Project.unit<2>.triggerPortWidth<0>=40
Project.unit<2>.triggerPortWidth<1>=2
Project.unit<2>.triggerPortWidth<2>=40
Project.unit<2>.triggerSequencerLevels=16
Project.unit<2>.triggerSequencerType=1
Project.unit<2>.type=ilapro
Project.unit<3>.clockChannel=gbtExmplDsgn RX_FRAMECLK_O
Project.unit<3>.clockEdge=Rising
Project.unit<3>.dataChannel<0>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<0>
Project.unit<3>.dataChannel<100>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<100>
Project.unit<3>.dataChannel<101>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<101>
Project.unit<3>.dataChannel<102>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<102>
Project.unit<3>.dataChannel<103>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<103>
Project.unit<3>.dataChannel<104>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<104>
Project.unit<3>.dataChannel<105>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<105>
Project.unit<3>.dataChannel<106>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<106>
Project.unit<3>.dataChannel<107>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<107>
Project.unit<3>.dataChannel<108>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<108>
Project.unit<3>.dataChannel<109>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<109>
Project.unit<3>.dataChannel<10>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<10>
Project.unit<3>.dataChannel<110>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<110>
Project.unit<3>.dataChannel<111>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<111>
Project.unit<3>.dataChannel<112>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<112>
Project.unit<3>.dataChannel<113>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<113>
Project.unit<3>.dataChannel<114>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<114>
Project.unit<3>.dataChannel<115>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<115>
Project.unit<3>.dataChannel<116>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<116>
Project.unit<3>.dataChannel<117>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<117>
Project.unit<3>.dataChannel<118>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<118>
Project.unit<3>.dataChannel<119>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<119>
Project.unit<3>.dataChannel<11>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<11>
Project.unit<3>.dataChannel<120>=gbtExmplDsgn RX_DATA_O<0>
Project.unit<3>.dataChannel<121>=gbtExmplDsgn RX_DATA_O<1>
Project.unit<3>.dataChannel<122>=gbtExmplDsgn RX_DATA_O<2>
Project.unit<3>.dataChannel<123>=gbtExmplDsgn RX_DATA_O<3>
Project.unit<3>.dataChannel<124>=gbtExmplDsgn RX_DATA_O<4>
Project.unit<3>.dataChannel<125>=gbtExmplDsgn RX_DATA_O<5>
Project.unit<3>.dataChannel<126>=gbtExmplDsgn RX_DATA_O<6>
Project.unit<3>.dataChannel<127>=gbtExmplDsgn RX_DATA_O<7>
Project.unit<3>.dataChannel<128>=gbtExmplDsgn RX_DATA_O<8>
Project.unit<3>.dataChannel<129>=gbtExmplDsgn RX_DATA_O<9>
Project.unit<3>.dataChannel<12>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<12>
Project.unit<3>.dataChannel<130>=gbtExmplDsgn RX_DATA_O<10>
Project.unit<3>.dataChannel<131>=gbtExmplDsgn RX_DATA_O<11>
Project.unit<3>.dataChannel<132>=gbtExmplDsgn RX_DATA_O<12>
Project.unit<3>.dataChannel<133>=gbtExmplDsgn RX_DATA_O<13>
Project.unit<3>.dataChannel<134>=gbtExmplDsgn RX_DATA_O<14>
Project.unit<3>.dataChannel<135>=gbtExmplDsgn RX_DATA_O<15>
Project.unit<3>.dataChannel<136>=gbtExmplDsgn RX_DATA_O<16>
Project.unit<3>.dataChannel<137>=gbtExmplDsgn RX_DATA_O<17>
Project.unit<3>.dataChannel<138>=gbtExmplDsgn RX_DATA_O<18>
Project.unit<3>.dataChannel<139>=gbtExmplDsgn RX_DATA_O<19>
Project.unit<3>.dataChannel<13>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<13>
Project.unit<3>.dataChannel<140>=gbtExmplDsgn RX_DATA_O<20>
Project.unit<3>.dataChannel<141>=gbtExmplDsgn RX_DATA_O<21>
Project.unit<3>.dataChannel<142>=gbtExmplDsgn RX_DATA_O<22>
Project.unit<3>.dataChannel<143>=gbtExmplDsgn RX_DATA_O<23>
Project.unit<3>.dataChannel<144>=gbtExmplDsgn RX_DATA_O<24>
Project.unit<3>.dataChannel<145>=gbtExmplDsgn RX_DATA_O<25>
Project.unit<3>.dataChannel<146>=gbtExmplDsgn RX_DATA_O<26>
Project.unit<3>.dataChannel<147>=gbtExmplDsgn RX_DATA_O<27>
Project.unit<3>.dataChannel<148>=gbtExmplDsgn RX_DATA_O<28>
Project.unit<3>.dataChannel<149>=gbtExmplDsgn RX_DATA_O<29>
Project.unit<3>.dataChannel<14>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<14>
Project.unit<3>.dataChannel<150>=gbtExmplDsgn RX_DATA_O<30>
Project.unit<3>.dataChannel<151>=gbtExmplDsgn RX_DATA_O<31>
Project.unit<3>.dataChannel<152>=gbtExmplDsgn RX_DATA_O<32>
Project.unit<3>.dataChannel<153>=gbtExmplDsgn RX_DATA_O<33>
Project.unit<3>.dataChannel<154>=gbtExmplDsgn RX_DATA_O<34>
Project.unit<3>.dataChannel<155>=gbtExmplDsgn RX_DATA_O<35>
Project.unit<3>.dataChannel<156>=gbtExmplDsgn RX_DATA_O<36>
Project.unit<3>.dataChannel<157>=gbtExmplDsgn RX_DATA_O<37>
Project.unit<3>.dataChannel<158>=gbtExmplDsgn RX_DATA_O<38>
Project.unit<3>.dataChannel<159>=gbtExmplDsgn RX_DATA_O<39>
Project.unit<3>.dataChannel<15>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<15>
Project.unit<3>.dataChannel<160>=gbtExmplDsgn RX_DATA_O<40>
Project.unit<3>.dataChannel<161>=gbtExmplDsgn RX_DATA_O<41>
Project.unit<3>.dataChannel<162>=gbtExmplDsgn RX_DATA_O<42>
Project.unit<3>.dataChannel<163>=gbtExmplDsgn RX_DATA_O<43>
Project.unit<3>.dataChannel<164>=gbtExmplDsgn RX_DATA_O<44>
Project.unit<3>.dataChannel<165>=gbtExmplDsgn RX_DATA_O<45>
Project.unit<3>.dataChannel<166>=gbtExmplDsgn RX_DATA_O<46>
Project.unit<3>.dataChannel<167>=gbtExmplDsgn RX_DATA_O<47>
Project.unit<3>.dataChannel<168>=gbtExmplDsgn RX_DATA_O<48>
Project.unit<3>.dataChannel<169>=gbtExmplDsgn RX_DATA_O<49>
Project.unit<3>.dataChannel<16>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<16>
Project.unit<3>.dataChannel<170>=gbtExmplDsgn RX_DATA_O<50>
Project.unit<3>.dataChannel<171>=gbtExmplDsgn RX_DATA_O<51>
Project.unit<3>.dataChannel<172>=gbtExmplDsgn RX_DATA_O<52>
Project.unit<3>.dataChannel<173>=gbtExmplDsgn RX_DATA_O<53>
Project.unit<3>.dataChannel<174>=gbtExmplDsgn RX_DATA_O<54>
Project.unit<3>.dataChannel<175>=gbtExmplDsgn RX_DATA_O<55>
Project.unit<3>.dataChannel<176>=gbtExmplDsgn RX_DATA_O<56>
Project.unit<3>.dataChannel<177>=gbtExmplDsgn RX_DATA_O<57>
Project.unit<3>.dataChannel<178>=gbtExmplDsgn RX_DATA_O<58>
Project.unit<3>.dataChannel<179>=gbtExmplDsgn RX_DATA_O<59>
Project.unit<3>.dataChannel<17>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<17>
Project.unit<3>.dataChannel<180>=gbtExmplDsgn RX_DATA_O<60>
Project.unit<3>.dataChannel<181>=gbtExmplDsgn RX_DATA_O<61>
Project.unit<3>.dataChannel<182>=gbtExmplDsgn RX_DATA_O<62>
Project.unit<3>.dataChannel<183>=gbtExmplDsgn RX_DATA_O<63>
Project.unit<3>.dataChannel<184>=gbtExmplDsgn RX_DATA_O<64>
Project.unit<3>.dataChannel<185>=gbtExmplDsgn RX_DATA_O<65>
Project.unit<3>.dataChannel<186>=gbtExmplDsgn RX_DATA_O<66>
Project.unit<3>.dataChannel<187>=gbtExmplDsgn RX_DATA_O<67>
Project.unit<3>.dataChannel<188>=gbtExmplDsgn RX_DATA_O<68>
Project.unit<3>.dataChannel<189>=gbtExmplDsgn RX_DATA_O<69>
Project.unit<3>.dataChannel<18>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<18>
Project.unit<3>.dataChannel<190>=gbtExmplDsgn RX_DATA_O<70>
Project.unit<3>.dataChannel<191>=gbtExmplDsgn RX_DATA_O<71>
Project.unit<3>.dataChannel<192>=gbtExmplDsgn RX_DATA_O<72>
Project.unit<3>.dataChannel<193>=gbtExmplDsgn RX_DATA_O<73>
Project.unit<3>.dataChannel<194>=gbtExmplDsgn RX_DATA_O<74>
Project.unit<3>.dataChannel<195>=gbtExmplDsgn RX_DATA_O<75>
Project.unit<3>.dataChannel<196>=gbtExmplDsgn RX_DATA_O<76>
Project.unit<3>.dataChannel<197>=gbtExmplDsgn RX_DATA_O<77>
Project.unit<3>.dataChannel<198>=gbtExmplDsgn RX_DATA_O<78>
Project.unit<3>.dataChannel<199>=gbtExmplDsgn RX_DATA_O<79>
Project.unit<3>.dataChannel<19>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<19>
Project.unit<3>.dataChannel<1>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<1>
Project.unit<3>.dataChannel<200>=gbtExmplDsgn RX_DATA_O<80>
Project.unit<3>.dataChannel<201>=gbtExmplDsgn RX_DATA_O<81>
Project.unit<3>.dataChannel<202>=gbtExmplDsgn RX_DATA_O<82>
Project.unit<3>.dataChannel<203>=gbtExmplDsgn RX_DATA_O<83>
Project.unit<3>.dataChannel<20>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<20>
Project.unit<3>.dataChannel<21>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<21>
Project.unit<3>.dataChannel<22>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<22>
Project.unit<3>.dataChannel<23>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<23>
Project.unit<3>.dataChannel<24>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<24>
Project.unit<3>.dataChannel<25>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<25>
Project.unit<3>.dataChannel<26>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<26>
Project.unit<3>.dataChannel<27>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<27>
Project.unit<3>.dataChannel<28>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<28>
Project.unit<3>.dataChannel<29>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<29>
Project.unit<3>.dataChannel<2>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<2>
Project.unit<3>.dataChannel<30>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<30>
Project.unit<3>.dataChannel<31>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<31>
Project.unit<3>.dataChannel<32>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<32>
Project.unit<3>.dataChannel<33>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<33>
Project.unit<3>.dataChannel<34>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<34>
Project.unit<3>.dataChannel<35>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<35>
Project.unit<3>.dataChannel<36>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<36>
Project.unit<3>.dataChannel<37>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<37>
Project.unit<3>.dataChannel<38>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<38>
Project.unit<3>.dataChannel<39>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<39>
Project.unit<3>.dataChannel<3>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<3>
Project.unit<3>.dataChannel<40>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<40>
Project.unit<3>.dataChannel<41>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<41>
Project.unit<3>.dataChannel<42>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<42>
Project.unit<3>.dataChannel<43>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<43>
Project.unit<3>.dataChannel<44>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<44>
Project.unit<3>.dataChannel<45>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<45>
Project.unit<3>.dataChannel<46>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<46>
Project.unit<3>.dataChannel<47>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<47>
Project.unit<3>.dataChannel<48>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<48>
Project.unit<3>.dataChannel<49>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<49>
Project.unit<3>.dataChannel<4>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<4>
Project.unit<3>.dataChannel<50>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<50>
Project.unit<3>.dataChannel<51>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<51>
Project.unit<3>.dataChannel<52>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<52>
Project.unit<3>.dataChannel<53>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<53>
Project.unit<3>.dataChannel<54>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<54>
Project.unit<3>.dataChannel<55>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<55>
Project.unit<3>.dataChannel<56>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<56>
Project.unit<3>.dataChannel<57>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<57>
Project.unit<3>.dataChannel<58>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<58>
Project.unit<3>.dataChannel<59>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<59>
Project.unit<3>.dataChannel<5>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<5>
Project.unit<3>.dataChannel<60>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<60>
Project.unit<3>.dataChannel<61>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<61>
Project.unit<3>.dataChannel<62>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<62>
Project.unit<3>.dataChannel<63>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<63>
Project.unit<3>.dataChannel<64>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<64>
Project.unit<3>.dataChannel<65>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<65>
Project.unit<3>.dataChannel<66>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<66>
Project.unit<3>.dataChannel<67>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<67>
Project.unit<3>.dataChannel<68>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<68>
Project.unit<3>.dataChannel<69>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<69>
Project.unit<3>.dataChannel<6>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<6>
Project.unit<3>.dataChannel<70>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<70>
Project.unit<3>.dataChannel<71>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<71>
Project.unit<3>.dataChannel<72>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<72>
Project.unit<3>.dataChannel<73>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<73>
Project.unit<3>.dataChannel<74>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<74>
Project.unit<3>.dataChannel<75>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<75>
Project.unit<3>.dataChannel<76>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<76>
Project.unit<3>.dataChannel<77>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<77>
Project.unit<3>.dataChannel<78>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<78>
Project.unit<3>.dataChannel<79>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<79>
Project.unit<3>.dataChannel<7>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<7>
Project.unit<3>.dataChannel<80>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<80>
Project.unit<3>.dataChannel<81>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<81>
Project.unit<3>.dataChannel<82>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<82>
Project.unit<3>.dataChannel<83>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<83>
Project.unit<3>.dataChannel<84>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<84>
Project.unit<3>.dataChannel<85>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<85>
Project.unit<3>.dataChannel<86>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<86>
Project.unit<3>.dataChannel<87>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<87>
Project.unit<3>.dataChannel<88>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<88>
Project.unit<3>.dataChannel<89>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<89>
Project.unit<3>.dataChannel<8>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<8>
Project.unit<3>.dataChannel<90>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<90>
Project.unit<3>.dataChannel<91>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<91>
Project.unit<3>.dataChannel<92>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<92>
Project.unit<3>.dataChannel<93>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<93>
Project.unit<3>.dataChannel<94>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<94>
Project.unit<3>.dataChannel<95>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<95>
Project.unit<3>.dataChannel<96>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<96>
Project.unit<3>.dataChannel<97>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<97>
Project.unit<3>.dataChannel<98>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<98>
Project.unit<3>.dataChannel<99>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<99>
Project.unit<3>.dataChannel<9>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<9>
Project.unit<3>.dataDepth=1024
Project.unit<3>.dataEqualsTrigger=true
Project.unit<3>.dataPortWidth=204
Project.unit<3>.enableGaps=false
Project.unit<3>.enableStorageQualification=true
Project.unit<3>.enableTimestamps=false
Project.unit<3>.timestampDepth=0
Project.unit<3>.timestampWidth=0
Project.unit<3>.triggerChannel<0><0>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<0>
Project.unit<3>.triggerChannel<0><100>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<100>
Project.unit<3>.triggerChannel<0><101>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<101>
Project.unit<3>.triggerChannel<0><102>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<102>
Project.unit<3>.triggerChannel<0><103>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<103>
Project.unit<3>.triggerChannel<0><104>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<104>
Project.unit<3>.triggerChannel<0><105>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<105>
Project.unit<3>.triggerChannel<0><106>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<106>
Project.unit<3>.triggerChannel<0><107>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<107>
Project.unit<3>.triggerChannel<0><108>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<108>
Project.unit<3>.triggerChannel<0><109>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<109>
Project.unit<3>.triggerChannel<0><10>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<10>
Project.unit<3>.triggerChannel<0><110>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<110>
Project.unit<3>.triggerChannel<0><111>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<111>
Project.unit<3>.triggerChannel<0><112>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<112>
Project.unit<3>.triggerChannel<0><113>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<113>
Project.unit<3>.triggerChannel<0><114>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<114>
Project.unit<3>.triggerChannel<0><115>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<115>
Project.unit<3>.triggerChannel<0><116>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<116>
Project.unit<3>.triggerChannel<0><117>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<117>
Project.unit<3>.triggerChannel<0><118>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<118>
Project.unit<3>.triggerChannel<0><119>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<119>
Project.unit<3>.triggerChannel<0><11>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<11>
Project.unit<3>.triggerChannel<0><12>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<12>
Project.unit<3>.triggerChannel<0><13>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<13>
Project.unit<3>.triggerChannel<0><14>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<14>
Project.unit<3>.triggerChannel<0><15>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<15>
Project.unit<3>.triggerChannel<0><16>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<16>
Project.unit<3>.triggerChannel<0><17>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<17>
Project.unit<3>.triggerChannel<0><18>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<18>
Project.unit<3>.triggerChannel<0><19>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<19>
Project.unit<3>.triggerChannel<0><1>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<1>
Project.unit<3>.triggerChannel<0><20>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<20>
Project.unit<3>.triggerChannel<0><21>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<21>
Project.unit<3>.triggerChannel<0><22>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<22>
Project.unit<3>.triggerChannel<0><23>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<23>
Project.unit<3>.triggerChannel<0><24>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<24>
Project.unit<3>.triggerChannel<0><25>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<25>
Project.unit<3>.triggerChannel<0><26>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<26>
Project.unit<3>.triggerChannel<0><27>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<27>
Project.unit<3>.triggerChannel<0><28>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<28>
Project.unit<3>.triggerChannel<0><29>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<29>
Project.unit<3>.triggerChannel<0><2>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<2>
Project.unit<3>.triggerChannel<0><30>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<30>
Project.unit<3>.triggerChannel<0><31>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<31>
Project.unit<3>.triggerChannel<0><32>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<32>
Project.unit<3>.triggerChannel<0><33>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<33>
Project.unit<3>.triggerChannel<0><34>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<34>
Project.unit<3>.triggerChannel<0><35>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<35>
Project.unit<3>.triggerChannel<0><36>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<36>
Project.unit<3>.triggerChannel<0><37>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<37>
Project.unit<3>.triggerChannel<0><38>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<38>
Project.unit<3>.triggerChannel<0><39>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<39>
Project.unit<3>.triggerChannel<0><3>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<3>
Project.unit<3>.triggerChannel<0><40>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<40>
Project.unit<3>.triggerChannel<0><41>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<41>
Project.unit<3>.triggerChannel<0><42>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<42>
Project.unit<3>.triggerChannel<0><43>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<43>
Project.unit<3>.triggerChannel<0><44>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<44>
Project.unit<3>.triggerChannel<0><45>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<45>
Project.unit<3>.triggerChannel<0><46>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<46>
Project.unit<3>.triggerChannel<0><47>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<47>
Project.unit<3>.triggerChannel<0><48>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<48>
Project.unit<3>.triggerChannel<0><49>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<49>
Project.unit<3>.triggerChannel<0><4>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<4>
Project.unit<3>.triggerChannel<0><50>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<50>
Project.unit<3>.triggerChannel<0><51>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<51>
Project.unit<3>.triggerChannel<0><52>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<52>
Project.unit<3>.triggerChannel<0><53>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<53>
Project.unit<3>.triggerChannel<0><54>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<54>
Project.unit<3>.triggerChannel<0><55>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<55>
Project.unit<3>.triggerChannel<0><56>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<56>
Project.unit<3>.triggerChannel<0><57>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<57>
Project.unit<3>.triggerChannel<0><58>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<58>
Project.unit<3>.triggerChannel<0><59>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<59>
Project.unit<3>.triggerChannel<0><5>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<5>
Project.unit<3>.triggerChannel<0><60>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<60>
Project.unit<3>.triggerChannel<0><61>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<61>
Project.unit<3>.triggerChannel<0><62>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<62>
Project.unit<3>.triggerChannel<0><63>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<63>
Project.unit<3>.triggerChannel<0><64>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<64>
Project.unit<3>.triggerChannel<0><65>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<65>
Project.unit<3>.triggerChannel<0><66>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<66>
Project.unit<3>.triggerChannel<0><67>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<67>
Project.unit<3>.triggerChannel<0><68>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<68>
Project.unit<3>.triggerChannel<0><69>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<69>
Project.unit<3>.triggerChannel<0><6>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<6>
Project.unit<3>.triggerChannel<0><70>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<70>
Project.unit<3>.triggerChannel<0><71>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<71>
Project.unit<3>.triggerChannel<0><72>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<72>
Project.unit<3>.triggerChannel<0><73>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<73>
Project.unit<3>.triggerChannel<0><74>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<74>
Project.unit<3>.triggerChannel<0><75>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<75>
Project.unit<3>.triggerChannel<0><76>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<76>
Project.unit<3>.triggerChannel<0><77>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<77>
Project.unit<3>.triggerChannel<0><78>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<78>
Project.unit<3>.triggerChannel<0><79>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<79>
Project.unit<3>.triggerChannel<0><7>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<7>
Project.unit<3>.triggerChannel<0><80>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<80>
Project.unit<3>.triggerChannel<0><81>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<81>
Project.unit<3>.triggerChannel<0><82>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<82>
Project.unit<3>.triggerChannel<0><83>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<83>
Project.unit<3>.triggerChannel<0><84>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<84>
Project.unit<3>.triggerChannel<0><85>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<85>
Project.unit<3>.triggerChannel<0><86>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<86>
Project.unit<3>.triggerChannel<0><87>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<87>
Project.unit<3>.triggerChannel<0><88>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<88>
Project.unit<3>.triggerChannel<0><89>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<89>
Project.unit<3>.triggerChannel<0><8>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<8>
Project.unit<3>.triggerChannel<0><90>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<90>
Project.unit<3>.triggerChannel<0><91>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<91>
Project.unit<3>.triggerChannel<0><92>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<92>
Project.unit<3>.triggerChannel<0><93>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<93>
Project.unit<3>.triggerChannel<0><94>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<94>
Project.unit<3>.triggerChannel<0><95>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<95>
Project.unit<3>.triggerChannel<0><96>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<96>
Project.unit<3>.triggerChannel<0><97>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<97>
Project.unit<3>.triggerChannel<0><98>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<98>
Project.unit<3>.triggerChannel<0><99>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<99>
Project.unit<3>.triggerChannel<0><9>=gbtExmplDsgn gbtBank_1 gbtRx_gen[1].gbtRx rxGearbox RX_FRAME_O<9>
Project.unit<3>.triggerChannel<1><0>=gbtExmplDsgn RX_DATA_O<0>
Project.unit<3>.triggerChannel<1><10>=gbtExmplDsgn RX_DATA_O<10>
Project.unit<3>.triggerChannel<1><11>=gbtExmplDsgn RX_DATA_O<11>
Project.unit<3>.triggerChannel<1><12>=gbtExmplDsgn RX_DATA_O<12>
Project.unit<3>.triggerChannel<1><13>=gbtExmplDsgn RX_DATA_O<13>
Project.unit<3>.triggerChannel<1><14>=gbtExmplDsgn RX_DATA_O<14>
Project.unit<3>.triggerChannel<1><15>=gbtExmplDsgn RX_DATA_O<15>
Project.unit<3>.triggerChannel<1><16>=gbtExmplDsgn RX_DATA_O<16>
Project.unit<3>.triggerChannel<1><17>=gbtExmplDsgn RX_DATA_O<17>
Project.unit<3>.triggerChannel<1><18>=gbtExmplDsgn RX_DATA_O<18>
Project.unit<3>.triggerChannel<1><19>=gbtExmplDsgn RX_DATA_O<19>
Project.unit<3>.triggerChannel<1><1>=gbtExmplDsgn RX_DATA_O<1>
Project.unit<3>.triggerChannel<1><20>=gbtExmplDsgn RX_DATA_O<20>
Project.unit<3>.triggerChannel<1><21>=gbtExmplDsgn RX_DATA_O<21>
Project.unit<3>.triggerChannel<1><22>=gbtExmplDsgn RX_DATA_O<22>
Project.unit<3>.triggerChannel<1><23>=gbtExmplDsgn RX_DATA_O<23>
Project.unit<3>.triggerChannel<1><24>=gbtExmplDsgn RX_DATA_O<24>
Project.unit<3>.triggerChannel<1><25>=gbtExmplDsgn RX_DATA_O<25>
Project.unit<3>.triggerChannel<1><26>=gbtExmplDsgn RX_DATA_O<26>
Project.unit<3>.triggerChannel<1><27>=gbtExmplDsgn RX_DATA_O<27>
Project.unit<3>.triggerChannel<1><28>=gbtExmplDsgn RX_DATA_O<28>
Project.unit<3>.triggerChannel<1><29>=gbtExmplDsgn RX_DATA_O<29>
Project.unit<3>.triggerChannel<1><2>=gbtExmplDsgn RX_DATA_O<2>
Project.unit<3>.triggerChannel<1><30>=gbtExmplDsgn RX_DATA_O<30>
Project.unit<3>.triggerChannel<1><31>=gbtExmplDsgn RX_DATA_O<31>
Project.unit<3>.triggerChannel<1><32>=gbtExmplDsgn RX_DATA_O<32>
Project.unit<3>.triggerChannel<1><33>=gbtExmplDsgn RX_DATA_O<33>
Project.unit<3>.triggerChannel<1><34>=gbtExmplDsgn RX_DATA_O<34>
Project.unit<3>.triggerChannel<1><35>=gbtExmplDsgn RX_DATA_O<35>
Project.unit<3>.triggerChannel<1><36>=gbtExmplDsgn RX_DATA_O<36>
Project.unit<3>.triggerChannel<1><37>=gbtExmplDsgn RX_DATA_O<37>
Project.unit<3>.triggerChannel<1><38>=gbtExmplDsgn RX_DATA_O<38>
Project.unit<3>.triggerChannel<1><39>=gbtExmplDsgn RX_DATA_O<39>
Project.unit<3>.triggerChannel<1><3>=gbtExmplDsgn RX_DATA_O<3>
Project.unit<3>.triggerChannel<1><40>=gbtExmplDsgn RX_DATA_O<40>
Project.unit<3>.triggerChannel<1><41>=gbtExmplDsgn RX_DATA_O<41>
Project.unit<3>.triggerChannel<1><42>=gbtExmplDsgn RX_DATA_O<42>
Project.unit<3>.triggerChannel<1><43>=gbtExmplDsgn RX_DATA_O<43>
Project.unit<3>.triggerChannel<1><44>=gbtExmplDsgn RX_DATA_O<44>
Project.unit<3>.triggerChannel<1><45>=gbtExmplDsgn RX_DATA_O<45>
Project.unit<3>.triggerChannel<1><46>=gbtExmplDsgn RX_DATA_O<46>
Project.unit<3>.triggerChannel<1><47>=gbtExmplDsgn RX_DATA_O<47>
Project.unit<3>.triggerChannel<1><48>=gbtExmplDsgn RX_DATA_O<48>
Project.unit<3>.triggerChannel<1><49>=gbtExmplDsgn RX_DATA_O<49>
Project.unit<3>.triggerChannel<1><4>=gbtExmplDsgn RX_DATA_O<4>
Project.unit<3>.triggerChannel<1><50>=gbtExmplDsgn RX_DATA_O<50>
Project.unit<3>.triggerChannel<1><51>=gbtExmplDsgn RX_DATA_O<51>
Project.unit<3>.triggerChannel<1><52>=gbtExmplDsgn RX_DATA_O<52>
Project.unit<3>.triggerChannel<1><53>=gbtExmplDsgn RX_DATA_O<53>
Project.unit<3>.triggerChannel<1><54>=gbtExmplDsgn RX_DATA_O<54>
Project.unit<3>.triggerChannel<1><55>=gbtExmplDsgn RX_DATA_O<55>
Project.unit<3>.triggerChannel<1><56>=gbtExmplDsgn RX_DATA_O<56>
Project.unit<3>.triggerChannel<1><57>=gbtExmplDsgn RX_DATA_O<57>
Project.unit<3>.triggerChannel<1><58>=gbtExmplDsgn RX_DATA_O<58>
Project.unit<3>.triggerChannel<1><59>=gbtExmplDsgn RX_DATA_O<59>
Project.unit<3>.triggerChannel<1><5>=gbtExmplDsgn RX_DATA_O<5>
Project.unit<3>.triggerChannel<1><60>=gbtExmplDsgn RX_DATA_O<60>
Project.unit<3>.triggerChannel<1><61>=gbtExmplDsgn RX_DATA_O<61>
Project.unit<3>.triggerChannel<1><62>=gbtExmplDsgn RX_DATA_O<62>
Project.unit<3>.triggerChannel<1><63>=gbtExmplDsgn RX_DATA_O<63>
Project.unit<3>.triggerChannel<1><64>=gbtExmplDsgn RX_DATA_O<64>
Project.unit<3>.triggerChannel<1><65>=gbtExmplDsgn RX_DATA_O<65>
Project.unit<3>.triggerChannel<1><66>=gbtExmplDsgn RX_DATA_O<66>
Project.unit<3>.triggerChannel<1><67>=gbtExmplDsgn RX_DATA_O<67>
Project.unit<3>.triggerChannel<1><68>=gbtExmplDsgn RX_DATA_O<68>
Project.unit<3>.triggerChannel<1><69>=gbtExmplDsgn RX_DATA_O<69>
Project.unit<3>.triggerChannel<1><6>=gbtExmplDsgn RX_DATA_O<6>
Project.unit<3>.triggerChannel<1><70>=gbtExmplDsgn RX_DATA_O<70>
Project.unit<3>.triggerChannel<1><71>=gbtExmplDsgn RX_DATA_O<71>
Project.unit<3>.triggerChannel<1><72>=gbtExmplDsgn RX_DATA_O<72>
Project.unit<3>.triggerChannel<1><73>=gbtExmplDsgn RX_DATA_O<73>
Project.unit<3>.triggerChannel<1><74>=gbtExmplDsgn RX_DATA_O<74>
Project.unit<3>.triggerChannel<1><75>=gbtExmplDsgn RX_DATA_O<75>
Project.unit<3>.triggerChannel<1><76>=gbtExmplDsgn RX_DATA_O<76>
Project.unit<3>.triggerChannel<1><77>=gbtExmplDsgn RX_DATA_O<77>
Project.unit<3>.triggerChannel<1><78>=gbtExmplDsgn RX_DATA_O<78>
Project.unit<3>.triggerChannel<1><79>=gbtExmplDsgn RX_DATA_O<79>
Project.unit<3>.triggerChannel<1><7>=gbtExmplDsgn RX_DATA_O<7>
Project.unit<3>.triggerChannel<1><80>=gbtExmplDsgn RX_DATA_O<80>
Project.unit<3>.triggerChannel<1><81>=gbtExmplDsgn RX_DATA_O<81>
Project.unit<3>.triggerChannel<1><82>=gbtExmplDsgn RX_DATA_O<82>
Project.unit<3>.triggerChannel<1><83>=gbtExmplDsgn RX_DATA_O<83>
Project.unit<3>.triggerChannel<1><8>=gbtExmplDsgn RX_DATA_O<8>
Project.unit<3>.triggerChannel<1><9>=gbtExmplDsgn RX_DATA_O<9>
Project.unit<3>.triggerConditionCountWidth=0
Project.unit<3>.triggerMatchCount<0>=1
Project.unit<3>.triggerMatchCount<1>=1
Project.unit<3>.triggerMatchCountWidth<0><0>=0
Project.unit<3>.triggerMatchCountWidth<1><0>=0
Project.unit<3>.triggerMatchType<0><0>=1
Project.unit<3>.triggerMatchType<1><0>=1
Project.unit<3>.triggerPortCount=2
Project.unit<3>.triggerPortIsData<0>=true
Project.unit<3>.triggerPortIsData<1>=true
Project.unit<3>.triggerPortWidth<0>=120
Project.unit<3>.triggerPortWidth<1>=84
Project.unit<3>.triggerSequencerLevels=16
Project.unit<3>.triggerSequencerType=1
Project.unit<3>.type=ilapro
