#ChipScope Core Inserter Project File Version 3.0
#Wed Jan 08 00:14:01 CET 2014
Project.device.designInputFile=M\:\\project_gbt\\hdl_projects\\new_structure_20_40_xlx_7\\example_designs\\xilinx_k7v7\\kc705\\ise_project\\kc705_gbt_example_design_cs.ngc
Project.device.designOutputFile=M\:\\project_gbt\\hdl_projects\\new_structure_20_40_xlx_7\\example_designs\\xilinx_k7v7\\kc705\\ise_project\\kc705_gbt_example_design_cs.ngc
Project.device.deviceFamily=20
Project.device.enableRPMs=true
Project.device.outputDirectory=M\:\\project_gbt\\hdl_projects\\new_structure_20_40_xlx_7\\example_designs\\xilinx_k7v7\\kc705\\ise_project\\_ngo
Project.device.useSRL16=true
Project.filter.dimension=1
Project.filter<0>=
Project.icon.boundaryScanChain=1
Project.icon.enableExtTriggerIn=false
Project.icon.enableExtTriggerOut=false
Project.icon.triggerInPinName=
Project.icon.triggerOutPinName=
Project.unit.dimension=2
Project.unit<0>.clockChannel=gbtExmplDsgn TX_FRAMECLK_O
Project.unit<0>.clockEdge=Rising
Project.unit<0>.dataDepth=1024
Project.unit<0>.dataEqualsTrigger=true
Project.unit<0>.dataPortWidth=16
Project.unit<0>.enableGaps=false
Project.unit<0>.enableStorageQualification=true
Project.unit<0>.enableTimestamps=false
Project.unit<0>.timestampDepth=0
Project.unit<0>.timestampWidth=0
Project.unit<0>.triggerChannel<0><0>=gbtExmplDsgn TX_DATA_O<0>
Project.unit<0>.triggerChannel<0><10>=gbtExmplDsgn TX_DATA_O<10>
Project.unit<0>.triggerChannel<0><11>=gbtExmplDsgn TX_DATA_O<11>
Project.unit<0>.triggerChannel<0><12>=gbtExmplDsgn TX_DATA_O<12>
Project.unit<0>.triggerChannel<0><13>=gbtExmplDsgn TX_DATA_O<13>
Project.unit<0>.triggerChannel<0><14>=gbtExmplDsgn TX_DATA_O<14>
Project.unit<0>.triggerChannel<0><15>=gbtExmplDsgn TX_DATA_O<15>
Project.unit<0>.triggerChannel<0><16>=gbtExmplDsgn TX_DATA_O<16>
Project.unit<0>.triggerChannel<0><17>=gbtExmplDsgn TX_DATA_O<17>
Project.unit<0>.triggerChannel<0><18>=gbtExmplDsgn TX_DATA_O<18>
Project.unit<0>.triggerChannel<0><19>=gbtExmplDsgn TX_DATA_O<19>
Project.unit<0>.triggerChannel<0><1>=gbtExmplDsgn TX_DATA_O<1>
Project.unit<0>.triggerChannel<0><20>=gbtExmplDsgn TX_DATA_O<20>
Project.unit<0>.triggerChannel<0><21>=gbtExmplDsgn TX_DATA_O<21>
Project.unit<0>.triggerChannel<0><22>=gbtExmplDsgn TX_DATA_O<22>
Project.unit<0>.triggerChannel<0><23>=gbtExmplDsgn TX_DATA_O<23>
Project.unit<0>.triggerChannel<0><24>=gbtExmplDsgn TX_DATA_O<24>
Project.unit<0>.triggerChannel<0><25>=gbtExmplDsgn TX_DATA_O<25>
Project.unit<0>.triggerChannel<0><26>=gbtExmplDsgn TX_DATA_O<26>
Project.unit<0>.triggerChannel<0><27>=gbtExmplDsgn TX_DATA_O<27>
Project.unit<0>.triggerChannel<0><28>=gbtExmplDsgn TX_DATA_O<28>
Project.unit<0>.triggerChannel<0><29>=gbtExmplDsgn TX_DATA_O<29>
Project.unit<0>.triggerChannel<0><2>=gbtExmplDsgn TX_DATA_O<2>
Project.unit<0>.triggerChannel<0><30>=gbtExmplDsgn TX_DATA_O<30>
Project.unit<0>.triggerChannel<0><31>=gbtExmplDsgn TX_DATA_O<31>
Project.unit<0>.triggerChannel<0><32>=gbtExmplDsgn TX_DATA_O<32>
Project.unit<0>.triggerChannel<0><33>=gbtExmplDsgn TX_DATA_O<33>
Project.unit<0>.triggerChannel<0><34>=gbtExmplDsgn TX_DATA_O<34>
Project.unit<0>.triggerChannel<0><35>=gbtExmplDsgn TX_DATA_O<35>
Project.unit<0>.triggerChannel<0><36>=gbtExmplDsgn TX_DATA_O<36>
Project.unit<0>.triggerChannel<0><37>=gbtExmplDsgn TX_DATA_O<37>
Project.unit<0>.triggerChannel<0><38>=gbtExmplDsgn TX_DATA_O<38>
Project.unit<0>.triggerChannel<0><39>=gbtExmplDsgn TX_DATA_O<39>
Project.unit<0>.triggerChannel<0><3>=gbtExmplDsgn TX_DATA_O<3>
Project.unit<0>.triggerChannel<0><40>=gbtExmplDsgn TX_DATA_O<40>
Project.unit<0>.triggerChannel<0><41>=gbtExmplDsgn TX_DATA_O<41>
Project.unit<0>.triggerChannel<0><42>=gbtExmplDsgn TX_DATA_O<42>
Project.unit<0>.triggerChannel<0><43>=gbtExmplDsgn TX_DATA_O<43>
Project.unit<0>.triggerChannel<0><44>=gbtExmplDsgn TX_DATA_O<44>
Project.unit<0>.triggerChannel<0><45>=gbtExmplDsgn TX_DATA_O<45>
Project.unit<0>.triggerChannel<0><46>=gbtExmplDsgn TX_DATA_O<46>
Project.unit<0>.triggerChannel<0><47>=gbtExmplDsgn TX_DATA_O<47>
Project.unit<0>.triggerChannel<0><48>=gbtExmplDsgn TX_DATA_O<48>
Project.unit<0>.triggerChannel<0><49>=gbtExmplDsgn TX_DATA_O<49>
Project.unit<0>.triggerChannel<0><4>=gbtExmplDsgn TX_DATA_O<4>
Project.unit<0>.triggerChannel<0><50>=gbtExmplDsgn TX_DATA_O<50>
Project.unit<0>.triggerChannel<0><51>=gbtExmplDsgn TX_DATA_O<51>
Project.unit<0>.triggerChannel<0><52>=gbtExmplDsgn TX_DATA_O<52>
Project.unit<0>.triggerChannel<0><53>=gbtExmplDsgn TX_DATA_O<53>
Project.unit<0>.triggerChannel<0><54>=gbtExmplDsgn TX_DATA_O<54>
Project.unit<0>.triggerChannel<0><55>=gbtExmplDsgn TX_DATA_O<55>
Project.unit<0>.triggerChannel<0><56>=gbtExmplDsgn TX_DATA_O<56>
Project.unit<0>.triggerChannel<0><57>=gbtExmplDsgn TX_DATA_O<57>
Project.unit<0>.triggerChannel<0><58>=gbtExmplDsgn TX_DATA_O<58>
Project.unit<0>.triggerChannel<0><59>=gbtExmplDsgn TX_DATA_O<59>
Project.unit<0>.triggerChannel<0><5>=gbtExmplDsgn TX_DATA_O<5>
Project.unit<0>.triggerChannel<0><60>=gbtExmplDsgn TX_DATA_O<60>
Project.unit<0>.triggerChannel<0><61>=gbtExmplDsgn TX_DATA_O<61>
Project.unit<0>.triggerChannel<0><62>=gbtExmplDsgn TX_DATA_O<62>
Project.unit<0>.triggerChannel<0><63>=gbtExmplDsgn TX_DATA_O<63>
Project.unit<0>.triggerChannel<0><64>=gbtExmplDsgn TX_DATA_O<64>
Project.unit<0>.triggerChannel<0><65>=gbtExmplDsgn TX_DATA_O<65>
Project.unit<0>.triggerChannel<0><66>=gbtExmplDsgn TX_DATA_O<66>
Project.unit<0>.triggerChannel<0><67>=gbtExmplDsgn TX_DATA_O<67>
Project.unit<0>.triggerChannel<0><68>=gbtExmplDsgn TX_DATA_O<68>
Project.unit<0>.triggerChannel<0><69>=gbtExmplDsgn TX_DATA_O<69>
Project.unit<0>.triggerChannel<0><6>=gbtExmplDsgn TX_DATA_O<6>
Project.unit<0>.triggerChannel<0><70>=gbtExmplDsgn TX_DATA_O<70>
Project.unit<0>.triggerChannel<0><71>=gbtExmplDsgn TX_DATA_O<71>
Project.unit<0>.triggerChannel<0><72>=gbtExmplDsgn TX_DATA_O<72>
Project.unit<0>.triggerChannel<0><73>=gbtExmplDsgn TX_DATA_O<73>
Project.unit<0>.triggerChannel<0><74>=gbtExmplDsgn TX_DATA_O<74>
Project.unit<0>.triggerChannel<0><75>=gbtExmplDsgn TX_DATA_O<75>
Project.unit<0>.triggerChannel<0><76>=gbtExmplDsgn TX_DATA_O<76>
Project.unit<0>.triggerChannel<0><77>=gbtExmplDsgn TX_DATA_O<77>
Project.unit<0>.triggerChannel<0><78>=gbtExmplDsgn TX_DATA_O<78>
Project.unit<0>.triggerChannel<0><79>=gbtExmplDsgn TX_DATA_O<79>
Project.unit<0>.triggerChannel<0><7>=gbtExmplDsgn TX_DATA_O<7>
Project.unit<0>.triggerChannel<0><80>=gbtExmplDsgn TX_DATA_O<80>
Project.unit<0>.triggerChannel<0><81>=gbtExmplDsgn TX_DATA_O<81>
Project.unit<0>.triggerChannel<0><82>=gbtExmplDsgn TX_DATA_O<82>
Project.unit<0>.triggerChannel<0><83>=gbtExmplDsgn TX_DATA_O<83>
Project.unit<0>.triggerChannel<0><8>=gbtExmplDsgn TX_DATA_O<8>
Project.unit<0>.triggerChannel<0><9>=gbtExmplDsgn TX_DATA_O<9>
Project.unit<0>.triggerChannel<1><0>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_txresetfsm_i TXRESETDONE
Project.unit<0>.triggerConditionCountWidth=0
Project.unit<0>.triggerMatchCount<0>=1
Project.unit<0>.triggerMatchCount<1>=1
Project.unit<0>.triggerMatchCountWidth<0><0>=0
Project.unit<0>.triggerMatchCountWidth<1><0>=0
Project.unit<0>.triggerMatchType<0><0>=1
Project.unit<0>.triggerMatchType<1><0>=1
Project.unit<0>.triggerPortCount=2
Project.unit<0>.triggerPortIsData<0>=true
Project.unit<0>.triggerPortIsData<1>=true
Project.unit<0>.triggerPortWidth<0>=84
Project.unit<0>.triggerPortWidth<1>=1
Project.unit<0>.triggerSequencerLevels=16
Project.unit<0>.triggerSequencerType=1
Project.unit<0>.type=ilapro
Project.unit<1>.clockChannel=gbtExmplDsgn RX_FRAMECLK_O
Project.unit<1>.clockEdge=Rising
Project.unit<1>.dataDepth=1024
Project.unit<1>.dataEqualsTrigger=true
Project.unit<1>.dataPortWidth=92
Project.unit<1>.enableGaps=false
Project.unit<1>.enableStorageQualification=true
Project.unit<1>.enableTimestamps=false
Project.unit<1>.timestampDepth=0
Project.unit<1>.timestampWidth=0
Project.unit<1>.triggerChannel<0><0>=gbtExmplDsgn RX_DATA_O<0>
Project.unit<1>.triggerChannel<0><10>=gbtExmplDsgn RX_DATA_O<10>
Project.unit<1>.triggerChannel<0><11>=gbtExmplDsgn RX_DATA_O<11>
Project.unit<1>.triggerChannel<0><12>=gbtExmplDsgn RX_DATA_O<12>
Project.unit<1>.triggerChannel<0><13>=gbtExmplDsgn RX_DATA_O<13>
Project.unit<1>.triggerChannel<0><14>=gbtExmplDsgn RX_DATA_O<14>
Project.unit<1>.triggerChannel<0><15>=gbtExmplDsgn RX_DATA_O<15>
Project.unit<1>.triggerChannel<0><16>=gbtExmplDsgn RX_DATA_O<16>
Project.unit<1>.triggerChannel<0><17>=gbtExmplDsgn RX_DATA_O<17>
Project.unit<1>.triggerChannel<0><18>=gbtExmplDsgn RX_DATA_O<18>
Project.unit<1>.triggerChannel<0><19>=gbtExmplDsgn RX_DATA_O<19>
Project.unit<1>.triggerChannel<0><1>=gbtExmplDsgn RX_DATA_O<1>
Project.unit<1>.triggerChannel<0><20>=gbtExmplDsgn RX_DATA_O<20>
Project.unit<1>.triggerChannel<0><21>=gbtExmplDsgn RX_DATA_O<21>
Project.unit<1>.triggerChannel<0><22>=gbtExmplDsgn RX_DATA_O<22>
Project.unit<1>.triggerChannel<0><23>=gbtExmplDsgn RX_DATA_O<23>
Project.unit<1>.triggerChannel<0><24>=gbtExmplDsgn RX_DATA_O<24>
Project.unit<1>.triggerChannel<0><25>=gbtExmplDsgn RX_DATA_O<25>
Project.unit<1>.triggerChannel<0><26>=gbtExmplDsgn RX_DATA_O<26>
Project.unit<1>.triggerChannel<0><27>=gbtExmplDsgn RX_DATA_O<27>
Project.unit<1>.triggerChannel<0><28>=gbtExmplDsgn RX_DATA_O<28>
Project.unit<1>.triggerChannel<0><29>=gbtExmplDsgn RX_DATA_O<29>
Project.unit<1>.triggerChannel<0><2>=gbtExmplDsgn RX_DATA_O<2>
Project.unit<1>.triggerChannel<0><30>=gbtExmplDsgn RX_DATA_O<30>
Project.unit<1>.triggerChannel<0><31>=gbtExmplDsgn RX_DATA_O<31>
Project.unit<1>.triggerChannel<0><32>=gbtExmplDsgn RX_DATA_O<32>
Project.unit<1>.triggerChannel<0><33>=gbtExmplDsgn RX_DATA_O<33>
Project.unit<1>.triggerChannel<0><34>=gbtExmplDsgn RX_DATA_O<34>
Project.unit<1>.triggerChannel<0><35>=gbtExmplDsgn RX_DATA_O<35>
Project.unit<1>.triggerChannel<0><36>=gbtExmplDsgn RX_DATA_O<36>
Project.unit<1>.triggerChannel<0><37>=gbtExmplDsgn RX_DATA_O<37>
Project.unit<1>.triggerChannel<0><38>=gbtExmplDsgn RX_DATA_O<38>
Project.unit<1>.triggerChannel<0><39>=gbtExmplDsgn RX_DATA_O<39>
Project.unit<1>.triggerChannel<0><3>=gbtExmplDsgn RX_DATA_O<3>
Project.unit<1>.triggerChannel<0><40>=gbtExmplDsgn RX_DATA_O<40>
Project.unit<1>.triggerChannel<0><41>=gbtExmplDsgn RX_DATA_O<41>
Project.unit<1>.triggerChannel<0><42>=gbtExmplDsgn RX_DATA_O<42>
Project.unit<1>.triggerChannel<0><43>=gbtExmplDsgn RX_DATA_O<43>
Project.unit<1>.triggerChannel<0><44>=gbtExmplDsgn RX_DATA_O<44>
Project.unit<1>.triggerChannel<0><45>=gbtExmplDsgn RX_DATA_O<45>
Project.unit<1>.triggerChannel<0><46>=gbtExmplDsgn RX_DATA_O<46>
Project.unit<1>.triggerChannel<0><47>=gbtExmplDsgn RX_DATA_O<47>
Project.unit<1>.triggerChannel<0><48>=gbtExmplDsgn RX_DATA_O<48>
Project.unit<1>.triggerChannel<0><49>=gbtExmplDsgn RX_DATA_O<49>
Project.unit<1>.triggerChannel<0><4>=gbtExmplDsgn RX_DATA_O<4>
Project.unit<1>.triggerChannel<0><50>=gbtExmplDsgn RX_DATA_O<50>
Project.unit<1>.triggerChannel<0><51>=gbtExmplDsgn RX_DATA_O<51>
Project.unit<1>.triggerChannel<0><52>=gbtExmplDsgn RX_DATA_O<52>
Project.unit<1>.triggerChannel<0><53>=gbtExmplDsgn RX_DATA_O<53>
Project.unit<1>.triggerChannel<0><54>=gbtExmplDsgn RX_DATA_O<54>
Project.unit<1>.triggerChannel<0><55>=gbtExmplDsgn RX_DATA_O<55>
Project.unit<1>.triggerChannel<0><56>=gbtExmplDsgn RX_DATA_O<56>
Project.unit<1>.triggerChannel<0><57>=gbtExmplDsgn RX_DATA_O<57>
Project.unit<1>.triggerChannel<0><58>=gbtExmplDsgn RX_DATA_O<58>
Project.unit<1>.triggerChannel<0><59>=gbtExmplDsgn RX_DATA_O<59>
Project.unit<1>.triggerChannel<0><5>=gbtExmplDsgn RX_DATA_O<5>
Project.unit<1>.triggerChannel<0><60>=gbtExmplDsgn RX_DATA_O<60>
Project.unit<1>.triggerChannel<0><61>=gbtExmplDsgn RX_DATA_O<61>
Project.unit<1>.triggerChannel<0><62>=gbtExmplDsgn RX_DATA_O<62>
Project.unit<1>.triggerChannel<0><63>=gbtExmplDsgn RX_DATA_O<63>
Project.unit<1>.triggerChannel<0><64>=gbtExmplDsgn RX_DATA_O<64>
Project.unit<1>.triggerChannel<0><65>=gbtExmplDsgn RX_DATA_O<65>
Project.unit<1>.triggerChannel<0><66>=gbtExmplDsgn RX_DATA_O<66>
Project.unit<1>.triggerChannel<0><67>=gbtExmplDsgn RX_DATA_O<67>
Project.unit<1>.triggerChannel<0><68>=gbtExmplDsgn RX_DATA_O<68>
Project.unit<1>.triggerChannel<0><69>=gbtExmplDsgn RX_DATA_O<69>
Project.unit<1>.triggerChannel<0><6>=gbtExmplDsgn RX_DATA_O<6>
Project.unit<1>.triggerChannel<0><70>=gbtExmplDsgn RX_DATA_O<70>
Project.unit<1>.triggerChannel<0><71>=gbtExmplDsgn RX_DATA_O<71>
Project.unit<1>.triggerChannel<0><72>=gbtExmplDsgn RX_DATA_O<72>
Project.unit<1>.triggerChannel<0><73>=gbtExmplDsgn RX_DATA_O<73>
Project.unit<1>.triggerChannel<0><74>=gbtExmplDsgn RX_DATA_O<74>
Project.unit<1>.triggerChannel<0><75>=gbtExmplDsgn RX_DATA_O<75>
Project.unit<1>.triggerChannel<0><76>=gbtExmplDsgn RX_DATA_O<76>
Project.unit<1>.triggerChannel<0><77>=gbtExmplDsgn RX_DATA_O<77>
Project.unit<1>.triggerChannel<0><78>=gbtExmplDsgn RX_DATA_O<78>
Project.unit<1>.triggerChannel<0><79>=gbtExmplDsgn RX_DATA_O<79>
Project.unit<1>.triggerChannel<0><7>=gbtExmplDsgn RX_DATA_O<7>
Project.unit<1>.triggerChannel<0><80>=gbtExmplDsgn RX_DATA_O<80>
Project.unit<1>.triggerChannel<0><81>=gbtExmplDsgn RX_DATA_O<81>
Project.unit<1>.triggerChannel<0><82>=gbtExmplDsgn RX_DATA_O<82>
Project.unit<1>.triggerChannel<0><83>=gbtExmplDsgn RX_DATA_O<83>
Project.unit<1>.triggerChannel<0><8>=gbtExmplDsgn RX_DATA_O<8>
Project.unit<1>.triggerChannel<0><9>=gbtExmplDsgn RX_DATA_O<9>
Project.unit<1>.triggerChannel<1><0>=gbtExmplDsgn gbtBank_1 mgt mgtStd_gen.mgtStd gtxStdX1_gen.gtxStdX1 gt0_rxresetfsm_i RXRESETDONE
Project.unit<1>.triggerConditionCountWidth=0
Project.unit<1>.triggerMatchCount<0>=1
Project.unit<1>.triggerMatchCount<1>=1
Project.unit<1>.triggerMatchCountWidth<0><0>=0
Project.unit<1>.triggerMatchCountWidth<1><0>=0
Project.unit<1>.triggerMatchType<0><0>=1
Project.unit<1>.triggerMatchType<1><0>=1
Project.unit<1>.triggerPortCount=2
Project.unit<1>.triggerPortIsData<0>=true
Project.unit<1>.triggerPortIsData<1>=true
Project.unit<1>.triggerPortWidth<0>=84
Project.unit<1>.triggerPortWidth<1>=1
Project.unit<1>.triggerSequencerLevels=16
Project.unit<1>.triggerSequencerType=1
Project.unit<1>.type=ilapro
