######################################################
#
# XPS Tcl API script generated by PlanAhead
#
######################################################

cd "D:/cern/xilinx/sdkDev/planAhead_mine/project_3/project_3.srcs/sources_1/edk/module_1"
if { [xload new module_1.xmp] != 0 } {
  exit -1
}
xset arch virtex6
xset dev xc6vlx240t
xset package ff1156
xset speedgrade -1

xset binfo ML605

if { [xset hier sub] != 0 } {
  exit -1
}
xset hdl verilog
save proj
exit
