function [TX_O_0,TX_O_1,RX_O_0,RX_O_1,pcktCount,pcktCount_c,pChk_ic_0,flag_packet] = importfile(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   [TX_O_0,TX_O_1,RX_O_0,RX_O_1,pcktCount,pcktCount_c,pChk_ic_0,flag_packet]
%   = IMPORTFILE(FILE) reads data from the first worksheet in the Microsoft
%   Excel spreadsheet file named FILE and returns the data as column
%   vectors.
%
%   [TX_O_0,TX_O_1,RX_O_0,RX_O_1,pcktCount,pcktCount_c,pChk_ic_0,flag_packet]
%   = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   [TX_O_0,TX_O_1,RX_O_0,RX_O_1,pcktCount,pcktCount_c,pChk_ic_0,flag_packet]
%   = IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.
%
%	Non-numeric cells are replaced with: NaN
%
% Example:
%   [TX_O_0,TX_O_1,RX_O_0,RX_O_1,pcktCount,pcktCount_c,pChk_ic_0,flag_packet]
%   = importfile('trigout1.xlsx','trigout',1,1025);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2016/07/01 11:25:09

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 1;
    endRow = 1025;
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('C%d:J%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('C%d:J%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,2,3,4,5,6]);
raw = raw(:,[7,8]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
TX_O_0 = cellVectors(:,1);
TX_O_1 = cellVectors(:,2);
RX_O_0 = cellVectors(:,3);
RX_O_1 = cellVectors(:,4);
pcktCount = cellVectors(:,5);
pcktCount_c = cellVectors(:,6);
pChk_ic_0 = data(:,1);
flag_packet = data(:,2);

