# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/gbt_fpga/example_designs/xilinx_k7v7/vc707/xdc/vc707_gbt_exmpldsgn_io.xdc

# XDC: D:/gbt_fpga/example_designs/xilinx_k7v7/vc707/xdc/vc707_gbt_exmpldsgn_timingclosure.xdc

# IP: ip/xlx_k7v7_rx_dpram/xlx_k7v7_rx_dpram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xlx_k7v7_rx_dpram || ORIG_REF_NAME==xlx_k7v7_rx_dpram}]

# IP: ip/xlx_k7v7_tx_dpram/xlx_k7v7_tx_dpram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xlx_k7v7_tx_dpram || ORIG_REF_NAME==xlx_k7v7_tx_dpram}]
