# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/gbt_fpga/example_designs/xilinx_k7v7/vc707/vivado/vc707_gbt_example_design.cache/wt [current_project]
set_property parent.project_path D:/gbt_fpga/example_designs/xilinx_k7v7/vc707/vivado/vc707_gbt_example_design.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc707:part0:1.2 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet D:/gbt_fpga/example_designs/xilinx_k7v7/vc707/vivado/vc707_gbt_example_design.runs/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm_synth_1/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm.dcp
set_property used_in_implementation false [get_files D:/gbt_fpga/example_designs/xilinx_k7v7/vc707/vivado/vc707_gbt_example_design.runs/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm_synth_1/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm.dcp]
add_files -quiet D:/gbt_fpga/example_designs/xilinx_k7v7/vc707/vivado/vc707_gbt_example_design.runs/xlx_k7v7_tx_pll_synth_1/xlx_k7v7_tx_pll.dcp
set_property used_in_implementation false [get_files D:/gbt_fpga/example_designs/xilinx_k7v7/vc707/vivado/vc707_gbt_example_design.runs/xlx_k7v7_tx_pll_synth_1/xlx_k7v7_tx_pll.dcp]
add_files -quiet D:/gbt_fpga/example_designs/xilinx_k7v7/vc707/vivado/vc707_gbt_example_design.runs/xlx_k7v7_vio_synth_1/xlx_k7v7_vio.dcp
set_property used_in_implementation false [get_files D:/gbt_fpga/example_designs/xilinx_k7v7/vc707/vivado/vc707_gbt_example_design.runs/xlx_k7v7_vio_synth_1/xlx_k7v7_vio.dcp]
add_files -quiet D:/gbt_fpga/example_designs/xilinx_k7v7/vc707/vivado/vc707_gbt_example_design.runs/xlx_k7v7_vivado_debug_synth_1/xlx_k7v7_vivado_debug.dcp
set_property used_in_implementation false [get_files D:/gbt_fpga/example_designs/xilinx_k7v7/vc707/vivado/vc707_gbt_example_design.runs/xlx_k7v7_vivado_debug_synth_1/xlx_k7v7_vivado_debug.dcp]
read_ip D:/gbt_fpga/example_designs/xilinx_k7v7/vc707/vivado/vc707_gbt_example_design.srcs/sources_1/ip/xlx_k7v7_rx_dpram/xlx_k7v7_rx_dpram.xci
set_property is_locked true [get_files D:/gbt_fpga/example_designs/xilinx_k7v7/vc707/vivado/vc707_gbt_example_design.srcs/sources_1/ip/xlx_k7v7_rx_dpram/xlx_k7v7_rx_dpram.xci]

read_ip D:/gbt_fpga/example_designs/xilinx_k7v7/vc707/vivado/vc707_gbt_example_design.srcs/sources_1/ip/xlx_k7v7_tx_dpram/xlx_k7v7_tx_dpram.xci
set_property is_locked true [get_files D:/gbt_fpga/example_designs/xilinx_k7v7/vc707/vivado/vc707_gbt_example_design.srcs/sources_1/ip/xlx_k7v7_tx_dpram/xlx_k7v7_tx_dpram.xci]

read_vhdl -library xil_defaultlib {
  D:/gbt_fpga/gbt_bank/xilinx_k7v7/xlx_k7v7_gbt_bank_package.vhd
  D:/gbt_fpga/gbt_bank/xilinx_k7v7/xlx_k7v7_gbt_banks_user_setup.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_bank_package.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_elpeval.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_chnsrch.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_errlcpoly.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_lmbddet.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_rs2errcor.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_syndrom.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_rx/gbt_rx_gearbox_std_rdctrl.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_polydiv.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox_std_rdwrctrl.vhd
  D:/gbt_fpga/gbt_bank/xilinx_k7v7/gbt_rx/xlx_k7v7_gbt_rx_gearbox_std_dpram.vhd
  D:/gbt_fpga/gbt_bank/xilinx_k7v7/gbt_tx/xlx_k7v7_gbt_tx_gearbox_std_dpram.vhd
  D:/gbt_fpga/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_gtx_sync_block.vhd
  D:/gbt_fpga/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_gtx_sync_pulse.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_deintlver.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder_gbtframe_rsdec.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_rx/gbt_rx_descrambler_16bit.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_rx/gbt_rx_descrambler_21bit.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner_bscounter.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner_pattsearch.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner_rightshift.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner_wraddr.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_rx/gbt_rx_gearbox_latopt.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_rx/gbt_rx_gearbox_std.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_intlver.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_tx/gbt_tx_encoder_gbtframe_rsencode.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox_latopt.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox_std.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_tx/gbt_tx_scrambler_16bit.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_tx/gbt_tx_scrambler_21bit.vhd
  D:/gbt_fpga/gbt_bank/core_sources/mgt/mgt_latopt_bitslipctrl.vhd
  D:/gbt_fpga/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_gtx_std.vhd
  D:/gbt_fpga/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_gtx_auto_phase_align.vhd
  D:/gbt_fpga/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_gtx_latopt.vhd
  D:/gbt_fpga/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_gtx_rx_manual_phase_align.vhd
  D:/gbt_fpga/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_gtx_rx_startup_fsm.vhd
  D:/gbt_fpga/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_gtx_tx_manual_phase_align.vhd
  D:/gbt_fpga/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_gtx_tx_startup_fsm.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_rx/gbt_rx_decoder.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_rx/gbt_rx_descrambler.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_rx/gbt_rx_framealigner.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_rx/gbt_rx_gearbox.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_rx/gbt_rx_status.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_tx/gbt_tx_encoder.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_tx/gbt_tx_scrambler.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_tx/gbt_tx_gearbox_phasemon.vhd
  D:/gbt_fpga/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_mgt_std.vhd
  D:/gbt_fpga/gbt_bank/xilinx_k7v7/mgt/xlx_k7v7_mgt_latopt.vhd
  D:/gbt_fpga/example_designs/core_sources/rxframeclk_phalgnr/phaligner_phase_computing.vhd
  D:/gbt_fpga/example_designs/core_sources/rxframeclk_phalgnr/phaligner_phase_comparator.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_rx/gbt_rx.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_tx/gbt_tx.vhd
  D:/gbt_fpga/gbt_bank/core_sources/mgt/multi_gigabit_transceivers.vhd
  D:/gbt_fpga/example_designs/xilinx_k7v7/core_sources/gbt_rx_frameclk_phalgnr/xlx_k7v7_phalgnr_std_mmcm.vhd
  D:/gbt_fpga/example_designs/xilinx_k7v7/core_sources/gbt_rx_frameclk_phalgnr/phaligner_mmcm_controller.vhd
  D:/gbt_fpga/example_designs/core_sources/rxframeclk_phalgnr/gbt_rx_frameclk_phalgnr.vhd
  D:/gbt_fpga/example_designs/core_sources/gbt_pattern_matchflag.vhd
  D:/gbt_fpga/example_designs/core_sources/gbt_pattern_generator.vhd
  D:/gbt_fpga/example_designs/core_sources/gbt_pattern_checker.vhd
  D:/gbt_fpga/example_designs/core_sources/gbt_bank_reset.vhd
  D:/gbt_fpga/gbt_bank/core_sources/gbt_bank.vhd
  D:/gbt_fpga/example_designs/xilinx_k7v7/core_sources/xlx_k7v7_reset.vhd
  D:/gbt_fpga/example_designs/xilinx_k7v7/core_sources/xlx_k7v7_gbt_example_design.vhd
  D:/gbt_fpga/example_designs/xilinx_k7v7/vc707/vc707_gbt_example_design.vhd
}
read_xdc D:/gbt_fpga/example_designs/xilinx_k7v7/vc707/xdc/vc707_gbt_exmpldsgn_io.xdc
set_property used_in_implementation false [get_files D:/gbt_fpga/example_designs/xilinx_k7v7/vc707/xdc/vc707_gbt_exmpldsgn_io.xdc]

read_xdc D:/gbt_fpga/example_designs/xilinx_k7v7/vc707/xdc/vc707_gbt_exmpldsgn_timingclosure.xdc
set_property used_in_implementation false [get_files D:/gbt_fpga/example_designs/xilinx_k7v7/vc707/xdc/vc707_gbt_exmpldsgn_timingclosure.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top vc707_gbt_example_design -part xc7vx485tffg1761-2
write_checkpoint -noxdef vc707_gbt_example_design.dcp
catch { report_utilization -file vc707_gbt_example_design_utilization_synth.rpt -pb vc707_gbt_example_design_utilization_synth.pb }
