# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/gbt_fpga/example_designs/xilinx_k7v7/core_sources/gbt_rx_frameclk_phalgnr/vivado/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm.xci
# IP: The module: 'xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/gbt_fpga/example_designs/xilinx_k7v7/core_sources/gbt_rx_frameclk_phalgnr/vivado/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/gbt_fpga/example_designs/xilinx_k7v7/core_sources/gbt_rx_frameclk_phalgnr/vivado/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/gbt_fpga/example_designs/xilinx_k7v7/core_sources/gbt_rx_frameclk_phalgnr/vivado/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/gbt_fpga/example_designs/xilinx_k7v7/core_sources/gbt_rx_frameclk_phalgnr/vivado/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: D:/gbt_fpga/example_designs/xilinx_k7v7/core_sources/gbt_rx_frameclk_phalgnr/vivado/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm.xci
# IP: The module: 'xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/gbt_fpga/example_designs/xilinx_k7v7/core_sources/gbt_rx_frameclk_phalgnr/vivado/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/gbt_fpga/example_designs/xilinx_k7v7/core_sources/gbt_rx_frameclk_phalgnr/vivado/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/gbt_fpga/example_designs/xilinx_k7v7/core_sources/gbt_rx_frameclk_phalgnr/vivado/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/gbt_fpga/example_designs/xilinx_k7v7/core_sources/gbt_rx_frameclk_phalgnr/vivado/xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlx_k7v7_gbt_rx_frameclk_phalgnr_mmcm'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
