// ax_data_issp.v

// Generated using ACDS version 16.0 211

`timescale 1 ps / 1 ps
module ax_data_issp (
		input  wire [200:0] probe,  //  probes.probe
		output wire [202:0] source  // sources.source
	);

	altsource_probe_top #(
		.sld_auto_instance_index ("YES"),
		.sld_instance_index      (0),
		.instance_id             ("NONE"),
		.probe_width             (201),
		.source_width            (203),
		.source_initial_value    ("0"),
		.enable_metastability    ("NO")
	) in_system_sources_probes_0 (
		.source     (source), // sources.source
		.probe      (probe),  //  probes.probe
		.source_ena (1'b1)    // (terminated)
	);

endmodule
