REM
REM   ____  ____
REM  /   /\/   /
REM /___/  \  /    Vendor: Xilinx
REM \   \   \/     Version : 1.4
REM  \   \         Application : Virtex-6 FPGA GTX Transceiver Wizard
REM  /   /         Filename : implement_sh.ejava
REM /___/   /\     Timestamp :
REM \   \  /  \
REM  \___\/\___\
REM
REM
REM implement.sh script
REM Generated by Xilinx Virtex-6 FPGA GTX Transceiver Wizard
REM

REM Clean results directory
REM Create results directory
REM Change current directory to results
ECHO WARNING: Removing existing results directory
RMDIR /S /Q results
MKDIR results

ECHO 'Running coregen on ICON required for example design'
coregen -b chipscope_icon_1.xco -p coregen.cgp
REM Check Results
IF ERRORLEVEL 0 GOTO PASS_COREGEN_ICON
ECHO An error occurred running coregen on ICON
GOTO END_IMPLEMENT_FAIL
:PASS_COREGEN_ICON
COPY ..\..\ibert.ngc .      

REM RUN Xst
ECHO 'Running Xst on Example top'
xst -ifn example_implement_ibert.xst -ofn example_core.log -intstyle silent
REM Check Results
IF ERRORLEVEL 0 GOTO PASS_XST
ECHO An error occurred running XST on example_ibert
GOTO END_IMPLEMENT_FAIL
:PASS_XST

REM Copy NGC Files
COPY chipscope_icon_1.ngc .\results\
COPY ..\..\ibert.ngc        .\results\
COPY example_ibert.ngc        .\results\
cd .\results

REM Run ngdbuild
ECHO 'Running NGDBUILD'
ngdbuild -uc ..\..\example_design\ibert_top.ucf -p xc6vlx130t-ff1156-1 -sd . example_ibert.ngc example_ibert_top.ngd
REM Check Results
IF ERRORLEVEL 0 GOTO PASS_NGDBUILD
ECHO An error occurred running NGDBUILD on example_ibert
GOTO END_IMPLEMENT_FAIL
:PASS_NGDBUILD
REM end run ngdbuild section

REM Run map
ECHO 'Running MAP'
map -w -p xc6vlx130t-ff1156-1 -o example_ibert_top.map.ncd example_ibert_top.ngd
REM Check Results
IF ERRORLEVEL 0 GOTO PASS_MAP
ECHO An error occurred running MAP on example_ibert
GOTO END_IMPLEMENT_FAIL
:PASS_MAP

REM Run par
ECHO 'Running PAR'
par -w -ol high example_ibert_top.map.ncd example_ibert_top.ncd
REM Check Results
IF ERRORLEVEL 0 GOTO PASS_PAR
ECHO An error occurred running PAR on example_ibert
GOTO END_IMPLEMENT_FAIL
:PASS_PAR
REM Report par results 

ECHO 'Running design through BITGEN'
bitgen -d -g GWE_cycle:Done -g GTS_cycle:Done -g DriveDone:Yes -g StartupClk:Cclk -w example_ibert_top.ncd
REM Check Results
IF ERRORLEVEL 0 GOTO PASS_BITGEN
ECHO An error occurred running BITGEN on example_ibert
GOTO END_IMPLEMENT_FAIL
:PASS_BITGEN

:END_IMPLEMENT_PASS
@CD ..
@ECHO PASS
@EXIT /B 0

:END_IMPLEMENT_FAIL
CD ..
ECHO FAIL
EXIT /B 1
