REM
REM   ____  ____
REM  /   /\/   /
REM /___/  \  /    Vendor: Xilinx
REM \   \   \/     Version : 1.06
REM  \   \         Application : ICON v1.06_a Core
REM  /   /         Filename : ise_implement.bat
REM /___/   /\     
REM \   \  /  \
REM  \___\/\___\
REM
REM
REM ise_implement.bat script
REM Generated by Xilinx ICON v1.06_a Core
REM

REM Clean results directory
REM Create results directory
REM Change current directory to results
ECHO WARNING: Removing existing results directory
RMDIR /S /Q results
MKDIR results

ECHO 'Running coregen on chipscope_vio required for Example Design'
coregen -b chipscope_vio.xco -p coregen.cgp
REM Check Results
IF ERRORLEVEL 0 GOTO PASS_COREGEN
ECHO An error occurred running coregen on chipscope_vio 
GOTO END_IMPLEMENT_FAIL
:PASS_COREGEN

REM RUN Xst
ECHO 'Running Xst on Example Design'
xst -ifn example_icon.xst -ofn example_core.log -intstyle silent
REM Check Results
IF ERRORLEVEL 0 GOTO PASS_XST
ECHO An error occurred running XST on example_icon
GOTO END_IMPLEMENT_FAIL
:PASS_XST

REM Copy NGC Files
COPY chipscope_vio.ngc  .\results\
COPY ..\..\icon.ngc        .\results\
COPY example_icon.ngc        .\results\
COPY chipscope_vio.ncf .\results\
COPY ..\..\icon.ncf        .\results\
cd .\results

REM Run ngdbuild
ECHO 'Running NGDBUILD'
ngdbuild -uc ..\..\example_design\example_icon.ucf -p xc6vlx240t-ff1156-1 -sd . example_icon.ngc example_icon.ngd
REM Check Results
IF ERRORLEVEL 0 GOTO PASS_NGDBUILD
ECHO An error occurred running NGDBUILD on example_icon
GOTO END_IMPLEMENT_FAIL
:PASS_NGDBUILD
REM end run ngdbuild section

REM Run map
ECHO 'Running MAP'
map -w -p xc6vlx240t-ff1156-1 -o example_icon.map.ncd example_icon.ngd
REM Check Results
IF ERRORLEVEL 0 GOTO PASS_MAP
ECHO An error occurred running MAP on example_icon
GOTO END_IMPLEMENT_FAIL
:PASS_MAP

REM Run par
ECHO 'Running PAR'
par -w -ol high example_icon.map.ncd example_icon.ncd 
REM Check Results
IF ERRORLEVEL 0 GOTO PASS_PAR
ECHO An error occurred running PAR on example_icon
GOTO END_IMPLEMENT_FAIL
:PASS_PAR
REM Report par results

ECHO 'Running design through BITGEN'
bitgen -d -g GWE_cycle:Done -g GTS_cycle:Done -g DriveDone:Yes -g StartupClk:Cclk -w example_icon.ncd
REM Check Results
IF ERRORLEVEL 0 GOTO PASS_BITGEN
ECHO An error occurred running BITGEN on example_icon
GOTO END_IMPLEMENT_FAIL
:PASS_BITGEN

:END_IMPLEMENT_PASS
@CD ..
@ECHO PASS
@EXIT /B 0

:END_IMPLEMENT_FAIL
CD ..
ECHO FAIL
EXIT /B 1
