// alt_ax_tx_dpram.v

// Generated using ACDS version 15.1 185

`timescale 1 ps / 1 ps
module alt_ax_tx_dpram (
		input  wire [159:0] data,      //  ram_input.datain
		input  wire [2:0]   wraddress, //           .wraddress
		input  wire [5:0]   rdaddress, //           .rdaddress
		input  wire         wren,      //           .wren
		input  wire         wrclock,   //           .wrclock
		input  wire         rdclock,   //           .rdclock
		output wire [19:0]  q          // ram_output.dataout
	);

	alt_ax_tx_dpram_ram_2port_151_4prucuq ram_2port_0 (
		.data      (data),      //  ram_input.datain
		.wraddress (wraddress), //           .wraddress
		.rdaddress (rdaddress), //           .rdaddress
		.wren      (wren),      //           .wren
		.wrclock   (wrclock),   //           .wrclock
		.rdclock   (rdclock),   //           .rdclock
		.q         (q)          // ram_output.dataout
	);

endmodule
