-- ax_data_issp.vhd

-- Generated using ACDS version 16.0 211

library IEEE;
library ax_data_issp_altera_in_system_sources_probes_160;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use ax_data_issp_altera_in_system_sources_probes_160.ax_data_issp_pkg.all;

entity ax_data_issp is
	port (
		probe  : in  std_logic_vector(200 downto 0) := (others => '0'); --  probes.probe
		source : out std_logic_vector(202 downto 0)                     -- sources.source
	);
end entity ax_data_issp;

architecture rtl of ax_data_issp is
begin

	in_system_sources_probes_0 : component ax_data_issp_altera_in_system_sources_probes_160.ax_data_issp_pkg.altsource_probe_top
		generic map (
			sld_auto_instance_index => "YES",
			sld_instance_index      => 0,
			instance_id             => "NONE",
			probe_width             => 201,
			source_width            => 203,
			source_initial_value    => "0",
			enable_metastability    => "NO"
		)
		port map (
			source     => source, -- sources.source
			probe      => probe,  --  probes.probe
			source_ena => '1'     -- (terminated)
		);

end architecture rtl; -- of ax_data_issp
