# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/gbt_fpga/example_designs/xilinx_k7v7/fc7/vivado_project/fc7_gbt_example_design.srcs/sources_1/ip/xlx_k7v7_rx_dpram/xlx_k7v7_rx_dpram.xci
# IP: The module: 'xlx_k7v7_rx_dpram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/gbt_fpga/example_designs/xilinx_k7v7/fc7/vivado_project/fc7_gbt_example_design.srcs/sources_1/ip/xlx_k7v7_rx_dpram/xlx_k7v7_rx_dpram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlx_k7v7_rx_dpram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/gbt_fpga/example_designs/xilinx_k7v7/fc7/vivado_project/fc7_gbt_example_design.srcs/sources_1/ip/xlx_k7v7_rx_dpram/xlx_k7v7_rx_dpram.xci
# IP: The module: 'xlx_k7v7_rx_dpram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/gbt_fpga/example_designs/xilinx_k7v7/fc7/vivado_project/fc7_gbt_example_design.srcs/sources_1/ip/xlx_k7v7_rx_dpram/xlx_k7v7_rx_dpram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlx_k7v7_rx_dpram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
