# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/gbt_fpga/example_designs/xilinx_k7v7/core_sources/tx_pll/vivado/xlx_k7v7_tx_pll.xci
# IP: The module: 'xlx_k7v7_tx_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/gbt_fpga/example_designs/xilinx_k7v7/core_sources/tx_pll/vivado/xlx_k7v7_tx_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlx_k7v7_tx_pll'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/gbt_fpga/example_designs/xilinx_k7v7/core_sources/tx_pll/vivado/xlx_k7v7_tx_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlx_k7v7_tx_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/gbt_fpga/example_designs/xilinx_k7v7/core_sources/tx_pll/vivado/xlx_k7v7_tx_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlx_k7v7_tx_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: D:/gbt_fpga/example_designs/xilinx_k7v7/core_sources/tx_pll/vivado/xlx_k7v7_tx_pll.xci
# IP: The module: 'xlx_k7v7_tx_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/gbt_fpga/example_designs/xilinx_k7v7/core_sources/tx_pll/vivado/xlx_k7v7_tx_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlx_k7v7_tx_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/gbt_fpga/example_designs/xilinx_k7v7/core_sources/tx_pll/vivado/xlx_k7v7_tx_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlx_k7v7_tx_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/gbt_fpga/example_designs/xilinx_k7v7/core_sources/tx_pll/vivado/xlx_k7v7_tx_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xlx_k7v7_tx_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
