-- mgt_atxpll_rst.vhd

-- Generated using ACDS version 16.0 211

library IEEE;
library mgt_atxpll_rst_altera_xcvr_reset_control_160;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use mgt_atxpll_rst_altera_xcvr_reset_control_160.mgt_atxpll_rst_pkg.all;

entity mgt_atxpll_rst is
	port (
		clock         : in  std_logic                    := '0'; --         clock.clk
		pll_powerdown : out std_logic_vector(0 downto 0);        -- pll_powerdown.pll_powerdown
		reset         : in  std_logic                    := '0'  --         reset.reset
	);
end entity mgt_atxpll_rst;

architecture rtl of mgt_atxpll_rst is
begin

	xcvr_reset_control_0 : component mgt_atxpll_rst_altera_xcvr_reset_control_160.mgt_atxpll_rst_pkg.altera_xcvr_reset_control
		generic map (
			CHANNELS              => 1,
			PLLS                  => 1,
			SYS_CLK_IN_MHZ        => 240,
			SYNCHRONIZE_RESET     => 1,
			REDUCED_SIM_TIME      => 1,
			TX_PLL_ENABLE         => 1,
			T_PLL_POWERDOWN       => 1000,
			SYNCHRONIZE_PLL_RESET => 0,
			TX_ENABLE             => 0,
			TX_PER_CHANNEL        => 0,
			T_TX_ANALOGRESET      => 0,
			T_TX_DIGITALRESET     => 20,
			T_PLL_LOCK_HYST       => 0,
			EN_PLL_CAL_BUSY       => 0,
			RX_ENABLE             => 0,
			RX_PER_CHANNEL        => 0,
			T_RX_ANALOGRESET      => 40,
			T_RX_DIGITALRESET     => 4000
		)
		port map (
			clock              => clock,         --         clock.clk
			reset              => reset,         --         reset.reset
			pll_powerdown      => pll_powerdown, -- pll_powerdown.pll_powerdown
			tx_analogreset     => open,          --   (terminated)
			tx_digitalreset    => open,          --   (terminated)
			tx_ready           => open,          --   (terminated)
			pll_locked         => "0",           --   (terminated)
			pll_select         => "0",           --   (terminated)
			tx_cal_busy        => "0",           --   (terminated)
			pll_cal_busy       => "0",           --   (terminated)
			tx_manual          => "1",           --   (terminated)
			rx_analogreset     => open,          --   (terminated)
			rx_digitalreset    => open,          --   (terminated)
			rx_ready           => open,          --   (terminated)
			rx_is_lockedtodata => "0",           --   (terminated)
			rx_cal_busy        => "0",           --   (terminated)
			rx_manual          => "0",           --   (terminated)
			tx_digitalreset_or => "0",           --   (terminated)
			rx_digitalreset_or => "0"            --   (terminated)
		);

end architecture rtl; -- of mgt_atxpll_rst
