######################################################
#
# XPS Tcl API script generated by PlanAhead
#
######################################################

proc _main_ {} {
  cd "D:/cern/xilinx/sdkDev/designFile_xilinxWiki/src/project/project_1/project_1.srcs/sources_1/edk/system"
  if { [ catch {xload xmp system.xmp} result ] } {
    exit 10
  }
  xset arch virtex6
  xset dev xc6vlx240t
  xset package ff1156
  xset speedgrade -1

xset binfo ML605

  save proj
  return $result
}

# Execute set part
if { [catch {_main_} result] } {
  exit -1
}

# Check return status and exit
if { [string length $result] == 0 } {
  exit 0
} else {
  exit $result
}
