config latoptimized_measurements_altera_jtag_avalon_master_151_nxrcxoa_cfg;
		design latoptimized_measurements_altera_jtag_avalon_master_151_nxrcxoa;
		instance latoptimized_measurements_altera_jtag_avalon_master_151_nxrcxoa.jtag_phy_embedded_in_jtag_master use latoptimized_measurements_altera_jtag_dc_streaming_100999897.altera_avalon_st_jtag_interface;
		instance latoptimized_measurements_altera_jtag_avalon_master_151_nxrcxoa.timing_adt use latoptimized_measurements_timing_adapter_151.latoptimized_measurements_timing_adapter_151_wojoliy;
		instance latoptimized_measurements_altera_jtag_avalon_master_151_nxrcxoa.fifo use latoptimized_measurements_altera_avalon_sc_fifo_151.altera_avalon_sc_fifo;
		instance latoptimized_measurements_altera_jtag_avalon_master_151_nxrcxoa.b2p use latoptimized_measurements_altera_avalon_st_bytes_to_packets_100999897.altera_avalon_st_bytes_to_packets;
		instance latoptimized_measurements_altera_jtag_avalon_master_151_nxrcxoa.p2b use latoptimized_measurements_altera_avalon_st_packets_to_bytes_100999897.altera_avalon_st_packets_to_bytes;
		instance latoptimized_measurements_altera_jtag_avalon_master_151_nxrcxoa.transacto use latoptimized_measurements_altera_avalon_packets_to_master_100999897.altera_avalon_packets_to_master;
		instance latoptimized_measurements_altera_jtag_avalon_master_151_nxrcxoa.b2p_adapter use latoptimized_measurements_channel_adapter_151.latoptimized_measurements_channel_adapter_151_ncvycvq;
		instance latoptimized_measurements_altera_jtag_avalon_master_151_nxrcxoa.p2b_adapter use latoptimized_measurements_channel_adapter_151.latoptimized_measurements_channel_adapter_151_q5glbkq;
		instance latoptimized_measurements_altera_jtag_avalon_master_151_nxrcxoa.rst_controller use latoptimized_measurements_altera_reset_controller_151.altera_reset_controller;
endconfig

